### ISSUE TITLE
Beviteli mező - többszörös feleletválasztós

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#10]
többszörös feleletválasztós

**Comment by maxinteger** [comment]
@zsebtanar te erre emlékszel, hogy ez mi akart lenni :)

**Comment by zsebtanar** [comment]
@maxinteger persze, arról van szó, hogy ha a megadott lehetőségek között nem csak 1, hanem több jó válasz is van ([példa](http://products.secureserver.net/images/surveys/multi_choice1.jpg))
