### ISSUE TITLE
Többszörös választási lehetőségnél megoldás egyértelmű jelölése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#106]
Nem egyértelmű, hogy többszörös választási lehetőségnél hogyan kell jelölni a megoldást. Jó lenne hibát dobni, ha valaki üresen akarja elmenteni a részfeladatot, mert most ezt is simán lehet.

**Comment by maxinteger** [comment]
@zsebtanar Átalakítottam, kérlek néz meg, hogy használhatóbb-e így. Ha igen akkor kérlek zárd is le a feladatot.

**Comment by maxinteger** [comment]
@zsebtanar Még is csak inkább lezárom és majd újra megnyitjuk ha valami nem az igazi.
