### ISSUE TITLE
Címkék, témakörök automatikus frissítése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#107]
Beviszek egy feladatot. Tegyük fel, hogy nincs az a témakör, amit szeretnék. Megnyitok egy új lapot, beviszem a témakört, elmentem, de a feladatnál a lista nem frissül. Jó lenne, ha frissülne, mert akkor nem kellene kilépni és újra megnyitni a feladatot, hogy lássam a frissen beírt elemet.

**Comment by maxinteger** [comment]
Nem mondom, hogy megoldhatatlan, de nem is egyszerű feladat.
Viszont ugyan erre a problémára ad választ a #41 feladat.
Szerintem inkább maradjunk annál ez pedig zárjuk le.
Addig is próbáld meg előre felvenni a szükséges elemeket, igyekszem előre venni a #41 feladatot :)
