### ISSUE TITLE
Feladat metaadatainak előbbre hozása

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#109]
Jó lenne, ha a metaadatok (kategória, osztály) az első tabban lennének. Továbbá, át lehetne nevezni a "kategóriák"-at pl. "adatlap"-ra, mert ez jobban jellemzi a tartalmat (a kategória csak az egyik mező).

**Comment by maxinteger** [comment]
@zsebtanar végül inkább "Metaadatok"-ra neveztem (az issue címéből), szerintem jobban tükrözi a fül tartalmát.
