### ISSUE TITLE
Második részfeladatra nem ugrik tovább

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#112]
Ha jól megoldottam az első részfeladatot, csak a megoldást látom, nem tudok továbblépni a következő részfeladatra.

![image](https://user-images.githubusercontent.com/13850825/34906970-82f8f8b4-f877-11e7-8787-229fcf919f3b.png)

**Comment by maxinteger** [comment]
@zsebtanar Lefekvés előtt még kipróbáltam az oldalt mobilon is és akkor nekem is előjött ez a hiba...
Javítottam
