### ISSUE TITLE
Megoldás mutatása részfeladatoknál

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#114]
Ha rákattintok a "megoldás" gombra, látszik a megoldás:

![image](https://user-images.githubusercontent.com/13850825/35068788-6c7cf554-fbd8-11e7-910b-0ab1560b6b7d.png)

Viszont ha nem, akkor nem:

![image](https://user-images.githubusercontent.com/13850825/35068809-790cc33a-fbd8-11e7-8e09-c5e94634a40e.png)

Az lenne a legjobb, ha alapból is lehetne látni a részfeladatoknál a megoldásokat.
pl:

**Comment by Mad31nCh3rn0b1l** [comment]
Most már rendben van a fejlesztőm, rárepülők erre kezdetnek :)

**Comment by maxinteger** [comment]
Done
