### ISSUE TITLE
Feladat szerkesztése archiválás/aktiválás után

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#118]
Ha egy feladatot archiválok/aktiválok, egyből kilép belőle. Jó lenne, ha csak a címke frissítődne, és tudnám tovább szerkeszteni.

**Comment by maxinteger** [comment]
@zsebtanar Mostantól minden mentés után a feladatszerkesztőben marad a felhasználó nem lép vissza a lista oldalra + beraktam egy töltés jelzőt is a mentés gombra
