### ISSUE TITLE
Zsebtanár prod átnevezése

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#119]

**Comment by maxinteger** [comment]
Tegnap megnéztem és sajnos nem lehet módosítani a projekt ID-t (ami a webcímben is szerepel). 
Az egyetlen járható út ha létrehozok egy új projektet és átmásolok mindent, de mivel a felasználókat nem lehet ezért újra kell regisztrálnotok.

**Comment by zsebtanar** [comment]
rendben, én benne vagyok. köszi, h utánajártál!

László Vadász <notifications@github.com> ezt írta (időpont: 2018. jan. 24.,
Sze 11:01):

**Comment by maxinteger** [comment]
@zsebtanar Kész is van
