### ISSUE TITLE
Belépés Facebook-fiókkal

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#12]

**Comment by maxinteger** [comment]
@zsebtanar 
Ehhez szükségem van egy Facebook AppID-ra. Ehhez előbb kell egy Facebook oldal, de nem vagyok benne biztos. Áron vagy te utánna tudnátok nézni mi kell ahhoz, hogy fent legyünk facebook-on, ha azek meg vannak én már létretudom hozni az appot, csak vegyetek fel mint aministrátor a létrehozott oldalhoz(?)

**Comment by zsebtanar** [comment]
@maxinteger létrehoztam egy app id-t: 248809925631434. az oldal: fejlesztői oldal: https://developers.facebook.com/apps/248809925631434/add/
facebook-oldal: https://www.facebook.com/zsebtanar
hozzáadtalak adminnak.

**Comment by maxinteger** [comment]
@zsebtanar Szuper és köszi

**Comment by zsebtanar** [comment]
👍 😃

**Comment by maxinteger** [comment]
@zsebtanar Biztos engem adtál hozzá, mert nem kaptam semmilyen értesítőt és a Facebook-ban sem látom, linkre kattintva pedig nem létező appra hivatkozik, rtudnál nézni újra, köszi

**Comment by zsebtanar** [comment]
nekem ezt írja ki, ha [ide](https://developers.facebook.com/apps/248809925631434/roles/) kattintok:
![image](https://user-images.githubusercontent.com/13850825/28591722-02bc8296-7187-11e7-9e08-5e517b1218ef.png)

**Comment by maxinteger** [comment]
Köszi, megpróbálok jobban beleásni ma hátha van valahol egy üzenet a FB-tól.
"Megnyugtató" hogy a FB ugyan olyan 💩  mint mikor 5 éve fejlesztettem rá

**Comment by zsebtanar** [comment]
😄

**Comment by maxinteger** [comment]
@zsebtanar Végül meg lett csak át kellett lépnem a facebook dev oldalra, azért vicces, hogy nem szólt a meghívóról

**Comment by zsebtanar** [comment]
@maxinteger ? ez érdekes. de az a lényeg, h akkor sikerült megoldani a problémát 👍
