### ISSUE TITLE
Érvénytelen feladat URL kezelése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#123]
Ha ezt írom be:
https://zsebtanar-prod.firebaseapp.com/exercise/-L3ZdL-M468KKZnlHQPG
akkor nem irányít át a honlap.

**Comment by zsebtanar** [comment]
amúgy bejelentkezés után is csak a fogaskereket mutatja. lehet, hogy ugyanaz a hiba?

**Comment by maxinteger** [comment]
@zsebtanar Jól tetted, hogy újat nyitottál.
Amúgy ez elvileg nem nehéz feladat, ha gondolod te is kijavíthatod ;)

**Comment by zsebtanar** [comment]
Rendben, megpróbálom.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. febr.
26., H 22:53):

**Comment by maxinteger** [comment]
Javítva
