### ISSUE TITLE
Szöveg igazítása markdown-ban

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#132]
Lehetőség a bekezdések középre és jobbra igazítására a markdown szövegben:

- [ ] markdown-it pluginek ellenerőzése, lehet már létezik ilyen
- [ ] ha nem létezik akkor a szükséges jelölések kitalálása és implementálása
- [ ] szerver és kliens oldalon is integrálni kell a plugint (a szerveren a szabad szavas kereső miatt kell)

**Comment by ldorogi** [comment]
markdown-it-center-text: ez a megadott szöveget igazítja középre, nem kifejezetten egy bekezdést, bár szerintem annak is lehet értelmezni (ha megadod pl.: ->Centered Text<-, akkor ezt egy ilyen html-é konvertálja: <div class="text-align-center">Centered Text</div>

**Comment by ldorogi** [comment]
Ez akart lenni: "<div class="text-align-center">Centered Text</div>"

**Comment by ldorogi** [comment]
´<div class="text-align-center">Centered Text</div>´

**Comment by ldorogi** [comment]
Na de hogyan lehet ide HTML kódot úgy beírni, hogy azt ne értelmezze html kódnak? :-)

**Comment by ldorogi** [comment]
->Centered Text<- => <<div class="text-align-center">Centered Text</div>>

**Comment by ldorogi** [comment]
`->Centered Text<- => <div class="text-align-center">Centered Text</div>`

**Comment by ldorogi** [comment]
Sikerült .....

**Comment by ldorogi** [comment]
Jobbra igazításra sajnos nincs plugin .....

**Comment by ldorogi** [comment]
A Viktorral megbeszéltek szerint csak a középre igazítást valósítjuk meg az említett plugin-el.

**Comment by zsebtanar** [comment]
rendben, ez így nagyon jó lesz!
