### ISSUE TITLE
Matematikai kifejezések (Katex)

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#15]
Néhány dolog, ami nem működik, pedig elvileg működnie kéne a [wiki](https://goo.gl/HDoHGH) szerint:
- [ ] \degree
- [ ] \overset (ez már benne van a masterban, csak még nem adták ki)

**Comment by maxinteger** [comment]
@zsebtanar Sajnos amíg nem adják ki hivatalosan is a 0.8.0-t addig nem egyszerű frissíteni rá, viszont így is javúlt a helyzet mert 0.6.0-ról 0.7.1-re váltottunk. Amint kijön a következő verzió frissítem a mi oldalunkon is.

**Comment by zsebtanar** [comment]
@maxinteger rendben, köszönöm szépen!
