### ISSUE TITLE
Több szám megoldás esetén változó sorrend opció

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#16]
Ennél a feladatnál a két megoldás sorrendje tetszőleges:
![image](https://user-images.githubusercontent.com/13850825/28182899-d81e2cce-680d-11e7-8568-d96dafe72a98.png)

**Comment by maxinteger** [comment]
Ehhez egy teljesen új beviteli mezőt javasolok sima sövegmezővel, de vesszóvel elválasztható elemekkel, hasonlítani a simple-text mezőre, csak több megoldást kellene megadni

**Comment by maxinteger** [comment]
@zsebtanar Ha nem gond akkor ezt a feladatot lezárom, mert a részfeladatok miatt értelmét vesztette, illetve nem sok haszna van felcserélni x1 és x2 mező sorrendjét főleg, hogy a cimke fix :)

**Comment by zsebtanar** [comment]
rendben. viszont ha van egy teszt, ahol több megoldási lehetőség közül kell
választani, akkor az opciókat random megkavarását érdemes lenne
implementálni.



2017. okt. 4. du. 12:59 ezt írta ("László Vadász" <notifications@github.com

**Comment by maxinteger** [comment]
@zsebtanar Az igaz-hamis és a többszörös felelet választó már most is támogatja a véletlenszerű keverést, veszek fel feladatot a sima felelet választóra

**Comment by zsebtanar** [comment]
Rendben, köszönöm.

2017. okt. 4. du. 2:19 ezt írta ("László Vadász" <notifications@github.com
>):

@zsebtanar <https://github.com/zsebtanar> Az igaz-hamis és a többszörös
felelet választó már most is támogatja a véletlenszerű keverést, veszek fel
feladatot a sima felelet választóra

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zsebtanar/zsebtanar-proto/issues/16#issuecomment-334137180>,
or mute the thread
