### ISSUE TITLE
Feladat klónozása nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#166]
### Elvárt viselkedés
Gomb segítségével feladat klónozható legyen.

### Jelenlegi viselkedés
A gombra kattintva hibajelzést ad:
![image](https://user-images.githubusercontent.com/13850825/37740027-865a7590-2d5c-11e8-9b9c-fb3d90ff77a0.png)

### Lépések a viselkedés reprodukálásához
- Hozz létre egy feladatot.
- Kattints a "feladat másolása" gombra.

**Comment by maxinteger** [comment]
javítva
