### ISSUE TITLE
Táblázat elcsúszott

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#17]
Utolsó oszlop túl szűk, gombok egymás alatt vannak.

![image](https://user-images.githubusercontent.com/13850825/28204228-6308d2d4-687d-11e7-8995-dfd151bb6483.png)

**Comment by zsebtanar** [comment]
@maxinteger valamiért nekem a google canary-ban továbbra sem működik... :( de a google chrome-ban igen - nagyon fura... :S

**Comment by maxinteger** [comment]
@zsebtanar Ez azért is fura mert még ki sem telepítettem :D 
Kb 5 perc és kint lesz

**Comment by zsebtanar** [comment]
@maxinteger Javagyúgy! 😄

**Comment by zsebtanar** [comment]
@maxinteger nem tudom, hogy már kitetted-e, de nekem még mindig ugyanolyan... :(

**Comment by maxinteger** [comment]
@zsebtanar kitettem és jónak tűnik Chrome 59-ben. Annyi, hogy továbbra is szétesik a táblázat ha az ablak keskenyebb mint 1000px, de már jó ideje nem lehet kapni 1024 alatti kijelzőt és különben is túl sok adat van a táblában ilyen keskeny nézethez...
Ha továbbra sem megy akkor próbáld meg frissíteni a bongésző cach-t, ha úgy se akkor nyísd újra a feladatot és beleásom magam kicsit.

**Comment by zsebtanar** [comment]
@maxinteger működik! köszi szépen! :D
