### ISSUE TITLE
Aktivált/archivált feladatok törlése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#173]
### Elvárt viselkedés
Aktivált/archivált feladatokat is lehessen törölni.

### Jelenlegi viselkedés
Nem lehet.

### Lépések a viselkedés reprodukálásához
- Hozz létre egy feladatot.
- Aktiváld.
- A törlés gomb eltűnik.

**Comment by maxinteger** [comment]
@zsebtanar Ha nem gond akkor ezt lezárom mert az apal probléma ugyan az mint #178

**Comment by zsebtanar** [comment]
Ok.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
29., Cs 10:45):
