### ISSUE TITLE
Archivált feladat törlése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#178]
### Elvárt viselkedés
Archivált feladatot is lehessen törölni.

### Jelenlegi viselkedés
Csak piszkozatban lévő feladatot lehet.

### Lépések a viselkedés reprodukálásához
- Hozz létre egy feladatot.
- Aktiváld.
- Archiváld.

**Comment by maxinteger** [comment]
@zsebtanar A törlési lehetőséget azért próbálom minimalizálni mert a draf-t után publikus a feladat és ha már valaki megoldotta akkor kérdéses, hogy mit fog látni ha töröljük a feladatot.
Amíg ezt eldöntjük addig az adminnak bekapcsolom. Később eselettleg tudunk egy ellenőrzést futtatni, hogy hányan oldották meg

**Comment by zsebtanar** [comment]
Rendben.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
29., Cs 10:55):

**Comment by zsebtanar** [comment]
@maxinteger egyébként sztem amíg nincsenek pontok, addig tök mindegy. utána már jobban oda kell figyelni rá... de lehet az, hogy csak a test-en lehet feladatot törölni, a prod-on már max módosítunk.
