### ISSUE TITLE
Feladatszerkesztő modal törlése modal bezárásakor

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#179]
### Elvárt viselkedés
A feladatszerkesztés közben (véletlenül) bezárok egy modalt, akkor ha újra megnyitom, ne vesszen el az adat.

### Jelenlegi viselkedés
Elveszik.

### Lépések a viselkedés reprodukálásához
- Hozz létre egy feladatot.
- Adj hozzá egy részfeladatot.
- Válassz ki egy beviteli mezőt és kezdd el szerkeszteni.
- Az "OK" gomb megnyomása nélkül zárd be a szerkesztőt.

**Comment by maxinteger** [comment]
@zsebtanar Sajnos ez normális viselkedés, nem nagyon tudok olyan szerkesztőt ahola bezárás nem azt jelenti, hogy "mégsem akarom a módosításokat". Azt viszont lehet, hogy ha módosítottál valamit akkor kérdezzen rá, hogy "biztos eldobod a módosításokat"?
De az is lehet, hogy ezek a véletlen bezárások azt jelzik, hogy rossz a UX, szóval lehet csak nagyobb ablak tér kell, vagy ne lehessen mindenhol a szürke háttérre kattintva bezárni a modal-t.
Mit gondolsz?

**Comment by zsebtanar** [comment]
Érdekes, hogy a Messenger-ben, ha elkezdek írni egy üzenetet valakinek, és
utána egy másik beszélgetésre kattintok, ha visszajövök, ugyanott tudom
folytatni, ahol abbahagytam. Nem lehet valahogy session-ben eltárolni
ezeket az adatokat? Ha nem, vagy nagyon macerás, akkor sztem első körben
legyen az, hogy a modalt csak az x-szel ill a "piszkozat elvetése" gombbal
lehet bezárni. Külön figyelmeztetés nem kell szerintem.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
28., Sze 23:11):

**Comment by maxinteger** [comment]
@zsebtanar sajnos ez nem ilyen egyszerű. A messager-ben alapvetően egy rettentő egyszerű felület a információ beveitel szempontjából, az üzenetek teljesen függetlenek egymástól és nyugodtan tárolható akárhol kár meddig, valamint az üzenetek közti váltás inkább a böngésző fülei közötti váltogatásra hasonlít mint sem a dialogusokra.
Ezzel szemben a zsebtanárban, vagy bármi más komlex probgramban (word, excel, stb.) nincs értelme hasonlónak mert az adatok között függőség van, tehát ha pl változik a megoldás mezők sorrendje, vagy törlöd azt amit az előbb még szerkezstettél vagy az egész al feladatot mozgatod, stb akkor a mentett adatokat is frissítni kellene egy igen bonyolúlt függőségi fa alapján úgy hogy 99% ay esély arra, hogy soha többet nem fogod pont azt módosítani.
Ráaásul a felugró ablakok úgy működnek minden programban, hogy a bezárás egyen értékű a "mégsem" funkcióval. Szóval még ha be is vezetnénk egy tárolás funkciót az más felhasználükat zavarhat, hogy eltérünk egy bevett UI működéstől + növeli a hibalehetőségeket is (Pl. módosítasz valamit, ne szándékosan bezárod a modált, majd később újra nyitod, de mást modosítasz és mented, de közben a korábbi módosításod is ott van amit nem akartál de még is ott van).
Röviden ez olyan funkció lenne ami automatikusan történik és a felhasználók 100% nem találkozott még vele.
Szóval vagy explicite megkérdezzük vagy a felhasználót, vagy alakítunk a UX-en.

**Comment by zsebtanar** [comment]
Ok, értettem. Akkor szerintem első körben legyen úgy, hogy alakítunk ux-en:
ha a modalon kívülre kattintasz, nem csukódik be automatikusan. Aztán ha ez
nem elég, visszatérünk rá. Ehhez mit szólsz?

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
29., Cs 10:34):

**Comment by maxinteger** [comment]
@zsebtanar Áll az alku

**Comment by zsebtanar** [comment]
Zsír! Köszi ;)

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
29., Cs 11:33):
