### ISSUE TITLE
Közönséges tört beviteli mező

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#181]
### Elvárt viselkedés
Közönséges törtet is lehessen választani beviteli mezőként.

### Jelenlegi viselkedés
Nincs ilyen funkció.

### Lépések a viselkedés reprodukálásához
N/A.

**Comment by maxinteger** [comment]
@zsebtanar Pontosan milyen beviteli mezőre lenne szükség? 
Én két számbeviteli mezőt tudok elképzelni egymás alatt. Te is ilyesmire gondoltál?

**Comment by zsebtanar** [comment]
Igen, esetleg egy törtvonal a kettő között. Ennek majd az ellenőrzése lesz
picit trükkösebb, mert egy törtet többféleképpen is föl lehet írni.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. márc.
28., Sze 22:33):
