### ISSUE TITLE
Keresés

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#19]
- [x] autocomplete search
- [x] egyből feladatok szövegét adja ki
- ~~találatok szűkítése osztályokra~~

Minta:
![zst_kereses](https://user-images.githubusercontent.com/13850825/28207929-b7ec34ae-688b-11e7-8b0a-feb4ebf37e7e.png)

**Comment by zsebtanar** [comment]
a redmenta feladatlapszerkesztőjénél az új feladatok hozzáadása hasonló módon történik:
![image](https://user-images.githubusercontent.com/13850825/28208006-f67578f2-688b-11e7-8ae5-19152da60954.png)

**Comment by maxinteger** [comment]
@zsebtanar 
Szerintem késznek tekinthetjük a kereső első fázisát.
Egyenlőre kihagytam az osztály szerinti szűrést, sőt a lapozást is (így csak az első 20 találatot adja ki).
Ha szükség lesz ezekre akkor azt majd egy külön feladatban megcsináljuk

**Comment by zsebtanar** [comment]
OK, rendben. Köszi szépen!

2017. okt. 4. du. 11:01 ezt írta ("László Vadász" <notifications@github.com

**Comment by maxinteger** [comment]
Hoppá, elfelejtettem telepíteni az új keresőt ... este javítom

**Comment by zsebtanar** [comment]
Rendben.

2017. okt. 5. de. 10:30 ezt írta ("László Vadász" <notifications@github.com

**Comment by zsebtanar** [comment]
Egy apró megjegyzés: van egy extra "m" a "Írj be legalább 2 karamktert a keresés megkezdéséhez."-ben.
