### ISSUE TITLE
Fogadó oldal feladat törlése után

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#195]
*[Olvass el](./contribution.md#feladatletrehozas)*

### Elvárt viselkedés
Feladat törlése után a feladatlista jelenjen meg.

### Jelenlegi viselkedés
Törlés után a link nem változik, az oldal hibaüzenetet ad:
![image](https://user-images.githubusercontent.com/13850825/38392673-a2e5142c-3928-11e8-8494-4c033697b360.png)

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1) Hozz létre egy listát
2) Töröld ki

**Comment by maxinteger** [comment]
@zsebtanar Ezt már javítottam
