### ISSUE TITLE
Admin fogadó oldal

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#198]
*[Olvass el](./contribution.md#feladatletrehozas)*

### Elvárt viselkedés
Ha egy admin bejelentkezik, egyből a feladatok listáját lássa.

### Jelenlegi viselkedés
Egy üdvözlőképernyőt lát.

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
Lépj be adminnal.

**Comment by maxinteger** [comment]
@zsebtanar Végül csak a linkeket módosítottam, továbbra is van nyitóoldal az admin-nak de ha az "Admin" linkre kattintasz akkor a feladatlistára ugrik, szerintem egyenlőre megteszi.

**Comment by zsebtanar** [comment]
@maxinteger ezt hol lehet tesztelni? van hozzá PR? a teszt-en továbbra is a fogadóoldalra mutat az "admin" link.

**Comment by zsebtanar** [comment]
@maxinteger teljesen jó. köszi szépen!
