### ISSUE TITLE
Feladat aktiválása létrehozás után

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#199]
*[Olvass el](./contribution.md#feladatletrehozas)*

### Elvárt viselkedés
Feladatot létrehozás után egyből lehessen aktiválni, amennyiben megfelel a kritériumoknak (van címe és van legalább 1 részfeladata).

### Jelenlegi viselkedés
A "További műveletek" alatti lista üres. Csak azután jelennek meg a listaelemek, ha a feladatot elmentettem és kiléptem a fő admin oldalra.

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1) Hozz létre egy új feladatot címmel és legalább egy részfeladattal
2) Kattints a "További opciók" gombra

**Comment by maxinteger** [comment]
@zsebtanar Elsősorban azért nem lehet egyből aktív feladatot létrehozni mert mindenképpen szükséges az feladat ellenőrzése. Maximum az adminnak elehetne megengedni, de szívem szerin ezt sem tenném :)

**Comment by zsebtanar** [comment]
sztem erre megoldás lehet az új *aktivált* feladatstátusz bevezetése (ld. #202)

**Comment by zsebtanar** [comment]
ez most már nem aktuális.
