### ISSUE TITLE
Beviteli mező - szöveges válasz

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#2]
Szabad szöveges beviteli mező

A feladat készítő...

- [ ] meg tud adni 1 vagy több lehetésges megoldást 
- [ ] beállíthatja, hogy a szóközöket ne vegye figyelembe az ellenőrzés
- [ ] beállíthatja, hogy a kis/nagy betűk között ne tegyen különbséget az ellenőrzés
- [ ] beállíthatja a prefix szöveget (opcionlális)
- [ ] beállíthatja a postfix szöveget (opcionlális)

Az ezen felüli megkötéseket a feladat leírásában kell a feladat készítőjének megania

A feladat megoldásakor csak egy szövegmező jelenik meg a prefix és postfix szöveggel együtt

**Comment by zsebtanar** [comment]
módosítottam a nevet, hogy egységes legyen.
