### ISSUE TITLE
Random képek megjelenése föltöltésnél

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#205]
*[Olvass el](./contribution.md#feladatletrehozas)*

### Elvárt viselkedés
A kép föltöltésénél csak azok jelenjenek meg, amiket föltöltöttem.

### Jelenlegi viselkedés
Az egyik feladatnál csomó extra kép is megjelent (ld. lent).

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1) Lépj be adminnal
2) Nyisd meg [ezt](https://zsebtanar-test.firebaseapp.com/admin/exercise/edit/-L9gQD0Zo7SvsQXBEcFh) a feladatot
3) Kattints a "Képek"-re

![image](https://user-images.githubusercontent.com/13850825/38525473-c0e943ee-3c52-11e8-858f-9273cc26cd8e.png)

**Comment by maxinteger** [comment]
@zsebtanar Ezek nem random képek, mindegyik meg van a DB-ben és a fájl tárolóban is (pl mind a 7 `a` kép is fent van külön-külön)
Lehet inkább a feltöltéssel van gond. Más feladatoknál is fenn áll ez a gond?

**Comment by zsebtanar** [comment]
Nem, egyelőre csak ennél az egynél találkoztam ezzel. Sztem egyelőre
jegeljük ezt, ha máskor is lesz ilyen, akkor majd újra elővesszük.

2018-04-10 0:14 GMT+02:00 László Vadász <notifications@github.com>:

**Comment by maxinteger** [comment]
@zsebtanar Valószínűleg valami feltöltési baki lesz, legalább is az a része, hogy 10+ nem várt kép is bekerül a rendszerbe.
Javaslom a javításig egyesével töltsd fel a képeket és utána frissítsd az oldalt mielőtt új feltöltésbe kezdesz

**Comment by zsebtanar** [comment]
rendben.

2018. április 14. 22:53 László Vadász írta, <notifications@github.com>:

**Comment by zsebtanar** [comment]
@maxinteger az utóbbi időben nem fordult elő a hiba, így lezárom a jegyet. ha mégis előjön, újra elővesszük.
