### ISSUE TITLE
Főoldal átalakítása

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#207]
### Elvárt viselkedés

- [ ] ~korábban elkészített arculat alkalmazása a főoldalra~
- [ ] fejléc eltávolítása:
![image](https://user-images.githubusercontent.com/13850825/38579040-10fafd42-3d06-11e8-8360-9a61272cc181.png)

**Comment by maxinteger** [comment]
@zsebtanar szerintem a korábbi arculat felejtős, de erről már beszéltünk is. Térjünk vissza rá egy külön feladatban ha már Gergő is átfutotta.
