### ISSUE TITLE
Témakör feladatai

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#21]
lehet olyan szerintem, mint a mostani verzióban:
![image](https://user-images.githubusercontent.com/13850825/28210870-fb326432-6899-11e7-866e-63a5035b8c69.png)

**Comment by maxinteger** [comment]
@zsebtanar kész, de lehet, hogy hiányzik még ez-az :)

**Comment by zsebtanar** [comment]
@maxinteger sztem ezt is le lehet zárni - ha majd lesz még vmi, nyitunk új hibajegyet. 👍
