### ISSUE TITLE
Beviteli mező automatikus méretezése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#210]
### Elvárt viselkedés
- A beviteli mező mindig akkora legyen, amekkora input kell bele.
- Akár nőhet dinamikusan is növekedhet, mint pl. [ez itt](https://codepen.io/Momciloo/pen/bpyMbB)

**Comment by maxinteger** [comment]
@zsebtanar Erre valóban szükség van? Tudsz mondani példát ahol nem elég az mostani szélesség?

Jól át kell gondolni egy ilyen funkció bevezetését mert nagyon megtudja bonyolítani az UI kezelését különböző képernyő méreteken és könnyen tönkreteheti az oldalt elrendezését.

Szerintem ennek a funkciónak hosszú szöveges beviteli mezőknél van igazán haszna, illetve sokkal kezelhetőbb a probléma ha csak függőlegesen tud nőni a mező fix szélesség mellett (lásd github comment szöveg mezőjét)

Ha nincs tényleges haszna ennek a funkciónak akkor javaslom töröljük ezt a feladatot.

**Comment by zsebtanar** [comment]
@maxinteger nem azzal van a gond, hogy túl rövid a mező, sőt, ellenkezőleg, sztem sokszor túl hosszú. pl. [itt](https://zsebtanar-prod.firebaseapp.com/exercise/-L8MUCLqJ5DatbP9srlb). azt esetleg nem lehet, hogy maximum szélességnek beállítjuk azt, ami most is van, és minimumnak pedig egy kisebbet? arról mit gondolsz, ami most a zsebtanar.hu-n van (pl. [itt)?](http://www.zsebtanar.hu/5/Alapmuveletek/Szamjegyek)
