### ISSUE TITLE
UTF8 használatának engedélyezése Katex-ben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#211]
### Elvárt viselkedés
UTF8 karaktert is meg lehessen jeleníteni Katex-ben.

### Jelenlegi viselkedés
Nem működik.

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1) Hozz létre egy feladatot
2) Írd be azt a feladat szövegébe, hogy ```$ő$```

**Comment by maxinteger** [comment]
A `allowAllSymbols: true` talán megoldja a problémát: https://github.com/Khan/KaTeX/pull/1217
de még nem adták ki azt ezt tartalmazó verziót. 
Később újra ránézek

**Comment by zsebtanar** [comment]
ok, akkor ezt napoljuk?

2018-04-14 22:46 GMT+02:00 László Vadász <notifications@github.com>:

**Comment by maxinteger** [comment]
@zsebtanar Elvileg a Katex 0.9 támogatja a utf-8 karaktereket is, de nekem nem nagyon működött.
Viszont ha `\text{...}` függvényt használod akkor simán működik pl: `\text{ő}` vagy `\text{kettő}`

**Comment by zsebtanar** [comment]
ok, sztem ezt akkor a #211-es PR-rel tekinthetjük lezártnak.

**Comment by maxinteger** [comment]
@zsebtanar pontosan
