### ISSUE TITLE
Felcserélhető sorrendű megoldások

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#212]
### Elvárt viselkedés
Ha egy feladatnak (pl. másodfokú egyenlet) több megoldása van, a két megoldást a válaszok sorrendjétől függetlenül fogadja el.

### Jelenlegi viselkedés
Csak egy adott megoldási sorrendet fogad el.

**Comment by maxinteger** [comment]
@zsebtanar Ezt nem értem. Részfeladaton belül bármilyen sorrendben beírhatók a megoldások és lényegében külön-külön is ellenőrizhető (még most)

**Comment by zsebtanar** [comment]
Tegyük fel, hogy van egy másodfokú egyenlet. A két megoldása 0 és 1. Ezt
jelen pillanatban csak úgy tudom megoldani, hogy két "szám" típusú beviteli
mezőt adok meg, az egyik 0 a másik 1.

A rendszer csak akkor fogadja el a megoldást, ha a felhasználó a két
megoldást **megfelelő sorrendben** írja be. Tehát ha ő az **elsőhöz** ír
1-et és a **másodikhoz** 0-t, akkor hibát fog kapni.

2018. április 14. 22:50 László Vadász írta, <notifications@github.com>:

**Comment by maxinteger** [comment]
@zsebtanar Köszi, most már értem a problémát. Sajnos ezt nem elehet megvalósítani a jelenlegi beviteli mezőkkel :(
Javaslom inkább egy új beviteli mező létrehozását.
Célszerű lenne olyan megoldást találni ami nem csak erre az egy problémára add megoldást, nem szeretném ha több tucat beviteli mezőnk lenne hasonló funkcionalitással :)

A következő az ötletem:
Egy "szám tömb" típus, pl.:

   Másodfokú egyenlet megoldásai: [______], [______] ...

A következő tulajdonságai lennének adminon:
 - Előtag (az inputok előtt - a példában ez "Másodfokú egyenlet megoldásai:")
 - Utótag (az inputok után - a példában ez "...")
 - Elválasztó karakter (az inputok között - a példában ez ", ")
 - Maximális tizedes jegyek száma
 - Sorrend számít (checkbox)
 - megoldások

Ezt a struktúrát akár halmazoknál is lehetne használni.
Te mit gondolsz Viktor, van olyan funkció ami még kellene ehhez az új típushoz, pl: elő/utótag minden input mezőhöz külön-külön? 
De akár teljesen mást is kitalálhatunk, várom a javaslataid.

**Comment by zsebtanar** [comment]
Ez sztem jó ötlet. Ami még hasznos funkció lehetne, hogy a megoldásokat
egymás mellett vagy opcionálisan egymás alatt jelenjenek meg. Ekkor már az
inputonként is jó lenne külön-külön elő/utótag. Ami még kérdés, hogy
szeretnénk-e más típusú megoldásokat is listába rendezni (pl. szöveg). Most
hirtelen nem jut eszembe olyan feladat, amihez ez kellene - a számlista
biztos gyakrabban fordul elő.

**Comment by maxinteger** [comment]
@zsebtanar viszont ha már egymás alá rakod a mezőket és van elő/utótag akkor azt feltételezem, hogy az elő/utótag egyértelművé teszti számok beírásának sorrendjét tehát használhatod a sima szám mezőt.
Ha szöveges bevitelre is szükség van akkor az külön feladat

**Comment by zsebtanar** [comment]
Attól, hogy egymás alá tesszük a mezőket, még lehet szó listáról: pl. a
másodfokú egyenletrendszer esetében. De kétségkívül az "inline" lenne a
fontosabb.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. ápr. 18.,
Sze 0:44):
