### ISSUE TITLE
Tesztelés közben szerzett tanulságok

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#219]
### Tanulságok, javaslatok (ömlesztve)
- Feleletválasztásnál ne használjunk olyan opciókat, amiket még nem tanultak
- Rossz megoldásnál legyen magyarázat
- Jó lenne, ha wifi nélkül is működne

### Kisebb-nagyobb észrevételek
- Fekete pipa helyett zöld pipa a jó részfeladat megoldásnál
- Keresésnél "math"-ra fura eredmény + címkék/témakörök között is keressen
- Szerkesztésnél képek nem jelennek meg a feleletválasztásnál
- Részfeladatoknál "kihagyható" opció (ezeket nem olyan fontosak, át lehet ugrani)

**Comment by maxinteger** [comment]
@zsebtanar Kérlek nézd át ezt a feladatot és készíts külön feladatot vagy github-os wiki oldalt az egyes pontokból majd zárjuk le ezt a feladatot

**Comment by zsebtanar** [comment]
@maxinteger az offline verziót külön feladatba tettem, a többit sztem lezárhatjuk.
