### ISSUE TITLE
Feladat megtekintése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#22]
Ez is lehet olyan szerintem, mint a mostani:
![image](https://user-images.githubusercontent.com/13850825/28210933-4cbf9464-689a-11e7-83c8-466bc85eedbb.png)

**Comment by maxinteger** [comment]
@zsebtanar kész, de lehet, hogy hiányzik még ez-az :)

**Comment by zsebtanar** [comment]
@maxinteger persze, ez még azért fog változni - de az tök jó, h a nagyja megvan! 👍
