### ISSUE TITLE
Facebook bejelentkezés nincs engedélyezve

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#220]
### Elvárt viselkedés
- Fb-kal is be lehessen jelentkezni.

### Jelenlegi viselkedés
- A "Bejelentkezés fb-kal" gombra kattintva ezt kapjuk:

![image](https://user-images.githubusercontent.com/13850825/38901886-56988f7a-429e-11e8-853f-fa0283408b64.png)

- Továbbá, az "engedélyezve" szóban is van egy elírás.

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
 1) Kattints a "Bejelentkezés Fb-kal" gombra

**Comment by maxinteger** [comment]
@zsebtanar szerintem teszten nincs is rá szükség

**Comment by zsebtanar** [comment]
@maxinteger prod-on sem működik. ha a gombra kattintok, egy pillanatig feljön egy fb-os ablak, de utána el is tűnik.

**Comment by maxinteger** [comment]
@zsebtanar Nem lehet, hogy azért mert be vagy már jelentkezve Facebook-on?
Próbáld ki ikognító módban is.

**Comment by zsebtanar** [comment]
Ezt kaptam:
![image](https://user-images.githubusercontent.com/13850825/39473234-10fea566-4d4e-11e8-83c6-d82ddf25e915.png)

**Comment by maxinteger** [comment]
@zsebtanar Szuper, csak egy kis konfiguraciós hiba. Elfelejtettem átállítni a Facebook app-ban URL a proto-rol a prod-ra. Este ránézek. Köszi, hogy kipróbáltad

**Comment by zsebtanar** [comment]
@maxinteger nincs mit. én köszönöm, h megnézed! :)

**Comment by maxinteger** [comment]
@zsebtanar Elvileg most már működik.

**Comment by zsebtanar** [comment]
@maxinteger jól látom, ugye, hogy csak a prod-on működik, a test-en továbbra sem?

**Comment by maxinteger** [comment]
@zsebtanar pontosan, de ahogy tegnap nézegettem a facebook app beállításokat, lehet megtudjuk oldalni, hogy a test-is tudja hasynálni.

Szeretnéd, hogy a teszten is lehessen használni a facebook opciót?
Mondjuk tesztelés céljából nem rossz ötlet :D

**Comment by zsebtanar** [comment]
@maxinteger ha nem nagy munka, akkor valóban jó lenne. de a prod a fontos, szóval a másik már nem akkora prioritás.

**Comment by zsebtanar** [comment]
@maxinteger rendben, nagyszerű! akkor ezt le leher zárni, ha jól sejtem.
