### ISSUE TITLE
Feladatok egybefolynak

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#222]
### Elvárt viselkedés
- Feladatok egyértelműen el legyenek választva.

### Jelenlegi viselkedés
- Feladatok elválasztása nem egyértelmű:
![image](https://user-images.githubusercontent.com/13850825/38902099-508bcdf8-429f-11e8-8fb2-03168a2cdcc6.png)

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
 1) Pl. [ide](https://zsebtanar-test.firebaseapp.com/grade/-KrmsXGraCOnZpC7lyPj) kattintva

**Comment by maxinteger** [comment]
@zsebtanar javaslom, hogy másik képernyőn is nézd meg az oldalt, mert pl a sárga figyelmeztető szöveg is olvasható és a tört vonal is jelen van ellenőrzés után és a mellékelt ábrán is jól láthatóak a keretezések.
Elég béna monitorom van és azon jól néz ki, lehet csak valami kalibrációs probléma van a te monitorodon.

Ettől függetlenül lehet még elbírna egy kis kiemelést :)

**Comment by zsebtanar** [comment]
Igazad van. A telefonon is megnézem, és ott is jobban lehet látni.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. ápr. 18.,
Sze 0:37):
