### ISSUE TITLE
Szövegközi beviteli mezők

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#226]
### Elvárt viselkedés
- Lehessen folyó szövegben, sortörés nélkül is megadni beviteli mezőket
- Az egyszerű feleletválasztó típusú feladatok legördülő menüben jelennének meg.

**Comment by maxinteger** [comment]
@zsebtanar Sajnos ez eléggé szembe megy azzal a koncepcióval amivel eddig dolgoztunk, azaz a leírás és a beviteli mező jól elkülönűl.

- Tudsz erre példát mutatni? 
- Milyen gyakran lenne rá szükség? 
- Milyen más alternatívák fogadhatók el?
- Át lehet úgy fogalmazni a szöveget, hogy ne kelljen a szöveg közepében megjeleníteni a mezőt?

**Comment by zsebtanar** [comment]
- Példa:

![image](https://user-images.githubusercontent.com/13850825/39473274-43d7a096-4d4e-11e8-960c-6ef6702b9866.png)

- Koordináták/intervallumok megadásakor lenne rá szükség (koordinátageometriában elég gyakoriak az ilyen feladatok)
- Alternatívák: nekem csak a feleletválasztós jut eszembe. Ez jó, de nem a legjobb, mert simán lehet tippelni.
- **Nem fontos, hogy a szöveg közepén jelenjen meg a beviteli mező.** Ha balra igazítva jelenik meg, az is tök jó.

**Comment by maxinteger** [comment]
@zsebtanar Áááá, így már értem mire gondoltál. Azt hittem a feladat leírás közepébe szeretnéd látni a beviteli mezőt.

Szerintem ezt a problémát meg lehet oldani a #212 -ben leírt beviteli mezővel.

**Comment by zsebtanar** [comment]
@maxinteger nagyszerű! :)

**Comment by zsebtanar** [comment]
@maxinteger és ilyen szted megoldható?

![image](https://user-images.githubusercontent.com/13850825/39480000-366c3700-4d67-11e8-94c8-fde071e3a487.png)

**Comment by maxinteger** [comment]
@zsebtanar talán, de ez legyen másik feladat, mert az utolsó két példád két teljesen más problémát ír körül.

**Comment by zsebtanar** [comment]
@maxinteger rendben, akkor erre létrehozok egy külön feladatot.

**Comment by maxinteger** [comment]
@zsebtanar Szerintem a #212 együtt ezt is lezárhatjuk
