### ISSUE TITLE
Negatív előjel nem működik bizonyos telefonoknál

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#232]
### Elvárt viselkedés
- Negatív számot is be lehessen írni megoldásként.

### Jelenlegi viselkedés
- Bizonyos telefonoknál (pl: Samsung galaxy j3 2017) nincs lehetőség negatív számokat beírni:

![image](https://user-images.githubusercontent.com/13850825/39398331-74f5fbee-4b0c-11e8-8656-ed6325da1e08.png)

### Környezet
 - szerver: prod
 - böngésző: Chrome
 - OS: Android
- telefon: Samsung galaxy j3 2017

**Comment by maxinteger** [comment]
@zsebtanar Betudnánd írni az android OS verziószámát (a Beállítások app-ban szokott lenni a lista végén), valamint a feladat URL-jét a böngészőből?

Most reggel néztem meg egy másik feladatot Android 6.0-n és volt mínusz karakter.

**Comment by maxinteger** [comment]
@zsebtanar azt hiszem megtaláltam a feladatot, de nálam továbbra is jó. Kipróbáltam iOS 11-en ott is jó.

Az a baj, hogy a legtöbb androidos gyártó lecseréli a beépített kinézetet és általában a billentyűzetet is és úgy tűnik ez nem sikerült valami jól az adott OS verzión a Samsungnál

**Comment by zsebtanar** [comment]
Holnap meg tudom kérdezni Robitól

László Vadász <notifications@github.com> ezt írta (időpont: 2018. ápr. 29.,
V 10:43):

**Comment by zsebtanar** [comment]
@maxinteger megnéztem a mouseflow-ban, és ott azt írja, hogy **Android 7.0 Nougat**

**Comment by maxinteger** [comment]
@zsebtanar ezzel kapcsolatban történt előrelépés?

**Comment by zsebtanar** [comment]
@maxinteger tudtommal nem, azonkívül, hogy megadtam az Android verziószámát.

**Comment by maxinteger** [comment]
@zsebtanar találtam valamit, úgy tűnik ez Samsung specifikus probléma és ott is csak a Samsung által alapértelmezetten bekapcsolt alternatív billentyűzetnél jön elő, tehát ha a felhasználó vissza vált a gyári google billentyűzetre vagy a más app-ot használ (pl Swift) akkor nem jelentkezik a probléma:
https://stackoverflow.com/questions/21677695/input-type-number-not-possible-to-insert-negative-numbers-on-mobile-phone

Sajnos a böngészőből nem tudjuk átváltani a billentyűzetet és a felhasználót sem szerencsés megkérni erre, hogy csak a mi kedvünkért tegye meg.

Az alábbi opció maradt.
1) kipróbáljuk az `inputmode="number"` attribútumot a szám mezőkön
2) megpróbáljuk alapértelmezetten negatív értékre állítani a mezőt majd kitörölni az értéket
3) ha két ponttal kezdi a számot a felhasználó akkor azt negatívnak vesszük 
4) előjel gomb beépítése

Utóbbi hármat leszűkíthetjük csak Samsung telefonokra

**Comment by maxinteger** [comment]
Sajnos nincs triviális megoldás a problémára. Saját virtuális billentyűzetre lesz szükség. Ehhez létrehozok egy új feladatot.
