### ISSUE TITLE
Függőség frissítés github biztonsági figyelmeztetés miatt

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#233]
A cloud function függőségek között a `hapijs / hoek` 4.2.1-es verziója sérülékeny frissíteni kell

**Comment by maxinteger** [comment]
Úgy tűnik a `firebase-admin` egyik al-al-al-alfüggősége okozza a problémát, de szerintem ez nem jelent közvetlen veszélyt jelenleg.

Remélhetőleg `firebase-admin` haarosan frissíti a saját függőségeit.

**Comment by zsebtanar** [comment]
Rendben. Köszi, hogy utánajártál!

László Vadász <notifications@github.com> ezt írta (időpont: 2018. ápr. 29.,
V 21:26):

**Comment by zsebtanar** [comment]
@maxinteger ez még él?

**Comment by maxinteger** [comment]
@zsebtanar igen, várok amíg frissítik a csomagot és akkor én is frissítem a Zsebtanárban

**Comment by zsebtanar** [comment]
@maxinteger rendben, köszi!

**Comment by maxinteger** [comment]
@zsebtanar nem akarok beleszólni, mert nem zavar ha teljes üzenettel reagálsz a sikeres frissítésekre, de lehet kényelmesebb a megjegyzés jobb felső sarkában lévő mosolzgós ikon használata és egy +1
;)

**Comment by maxinteger** [comment]
Frissítettem a függősségeket és nincs több kritikus hiba, továbbá mostantól a greenkeeper segítségével fogunk frissíteni
