### ISSUE TITLE
Kitörölt témakör nem tűnik el

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#234]
### Elvárt viselkedés
- Ha egy feladatnál az egyik kategóriát törlöm, de jelenjen meg többet ott a kezdőlapon.

### Jelenlegi viselkedés
- Továbbra is megjelenik

### Környezet
- szerver: test/prod
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1) Nézd meg [ezt](https://zsebtanar-test.firebaseapp.com/admin/exercise/edit/-LBCU-jFG_bHv0-MBjfC) a feladatot
2) A kezdőlapon az Érettségi feladatoknál is megjelenik, noha a kategóriából ezt már kitöröltem

**Comment by maxinteger** [comment]
Nagyon gyanús, hogy ez összefügg a #194 feladattal

**Comment by zsebtanar** [comment]
@maxinteger vsz igen.
