### ISSUE TITLE
Feladat előnézete nyersformátumban

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#236]
### Elvárt viselkedés
- A feladatot ne csak a Katex általi feldolgozás után, hanem nyersformátumban (pl. $$x^2$$) is meg lehessen megnézni.
- Ennek az lenne az előnye, hogy bizonyos részeket (pl. másodfokú egyenlet megoldóképletét) könnyen fel lehetne használni más feladatoknál.

**Comment by maxinteger** [comment]
@zsebtanar Ha csak azért van erre szükség mert bonyolúlt katex formuákat szeretbél kimásolni akkor szerintem jobb ha készítünk egy listát ezekről és beépítjük a szüvegszerkesztőbe.

Van más oka is annak, hogy a forrást szeretnéd látni?

**Comment by zsebtanar** [comment]
@maxinteger nem csak erről van szó, hanem ha pl. van egy feladat, aminek a részfeladatait hasonló módon lehet megoldani (pl. [ez](https://zsebtanar-prod.firebaseapp.com/exercise/-LBApgltjmebLWKsNWDJ)). ilyenkor jó lenne, ha egy-egy részfeladatot látnék "nyers" formátumban is, mert akkor ezeket tudom másolgatni (sztem az lenne a legjobb, ha az előnézetben lenne egy "nyersformátum" választó, amivel ki lehet kapcsolni a katex-et).

**Comment by maxinteger** [comment]
Szerintem ezt a feladatot nem triviális megoldani és nagy részt helyettesíthető a klónozás és a bővített szövegszerkesztő funkciókkal #69 ezért lezárom
