### ISSUE TITLE
Vektorok jelölése Katex-ben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#237]
### Elvárt viselkedés
- Vektorokat lehet jelölni az ```\overrightarrow{AB}``` paranccsal.
- [Elvileg](https://github.com/Khan/KaTeX/issues/402) a parancs már benne van a 0.8.0-s Katex-verzióban.

### Jelenlegi viselkedés
- A parancs nem működik.
- A ```\vec{AB}``` működik, de nem túl szép:
![image](https://user-images.githubusercontent.com/13850825/39450843-fef73bca-4ccc-11e8-9673-32482daad6c3.png)

**Comment by maxinteger** [comment]
@zsebtanar a 0.9.0-s katex-ben működik lást #211 -es feladat

**Comment by zsebtanar** [comment]
@maxinteger valóban.
