### ISSUE TITLE
Térköz beállítása Katex-ben többsoros egyenletnél

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#238]
### Elvárt viselkedés
- Többsoros egyenletnél ne folyjanak egybe a sorok.

### Jelenlegi viselkedés
- Határeset...:
![image](https://user-images.githubusercontent.com/13850825/39451676-afca3522-4ccf-11e8-8ebb-740d468e2167.png)

**Comment by maxinteger** [comment]
@zsebtanar betudod linkelni melyik feladatban volt a probléma, vagy legalább a katex kódot?

**Comment by zsebtanar** [comment]
@maxinteger [erről](https://zsebtanar-prod.firebaseapp.com/exercise/-LBNVvWlCkZWibELbB1H) a feladatról van szó. a #211-es PR-rel már sokkal jobb:

![image](https://user-images.githubusercontent.com/13850825/39551581-dbf73676-4e65-11e8-843c-b80d322948df.png)
