### ISSUE TITLE
Képek mutatása feladatszerkesztőben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#243]
### Elvárt viselkedés
- A képek jelenjenek meg a **Részfeladatok** > **Megoldások** almenüpontnál, illetve az **Előnézet**ben.
- Ez jelentősen megkönnyítené a hibakeresést.

### Jelenlegi viselkedés
**Részfeladatok** > **Megoldások**
![image](https://user-images.githubusercontent.com/13850825/39595069-ba91b75a-4f0e-11e8-81ab-05c9056bfaa5.png)

**Előnézet**
![image](https://user-images.githubusercontent.com/13850825/39595033-98660302-4f0e-11e8-994d-415947117f29.png)

### Lépések a viselkedés reprodukálásához
[Koszinuszos feladat 1. részfeladat](https://zsebtanar-prod.firebaseapp.com/admin/exercise/edit/-L9gQD0Zo7SvsQXBEcFh)

**Comment by zsebtanar** [comment]
@maxinteger most látom, hogy az előnézetben betöltődnek a képek, csak lassan.

**Comment by maxinteger** [comment]
@zsebtanar nálam betöltődnek a képek, próbáld meg frissíteni az oldalt. Ha továbbra is előfordul akkor újra nyithatjuk ezt a feladatot.

**Comment by zsebtanar** [comment]
@maxinteger az előnézetnél valóban betölt, viszont a megoldásoknál továbbra sem. Például [ennél](https://zsebtanar-test.firebaseapp.com/admin/exercise/edit/-L9gQD0Zo7SvsQXBEcFh) a feladatnál:

![image](https://user-images.githubusercontent.com/13850825/39616826-9a74fc9c-4f7d-11e8-923c-4dcebb6ae384.png)

**Comment by maxinteger** [comment]
@zsebtanar javítottam
