### ISSUE TITLE
Üres megoldások ellenőrzése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#25]
A ["Teszt Elek"](https://zsebtanar-proto-76083.firebaseapp.com/exercise/view/-KoxPZxP4KiRd_9h5TvJ) feladat üres megoldást is elfogad:
![image](https://user-images.githubusercontent.com/13850825/28211865-1ca49c3e-689f-11e7-9070-e9278a577812.png)

**Comment by zsebtanar** [comment]
![image](https://user-images.githubusercontent.com/13850825/28262882-0aa7cb94-6ae5-11e7-9c2f-871f3d8cad99.png)

**Comment by maxinteger** [comment]
@zsebtanar Még mindig jelen van a szöveges beviteli mezőnél?

**Comment by zsebtanar** [comment]
@maxinteger yep. meg a számosnál is... mindegyiknél.
![image](https://user-images.githubusercontent.com/13850825/28266118-7bfe52be-6af3-11e7-82b5-f5ba9d612408.png)

**Comment by maxinteger** [comment]
@zsebtanar mostmár tényleg jó lesz

**Comment by zsebtanar** [comment]
@maxinteger 👍 annyi, hogy most hibát jelez - nem lehet inkább, hogy csak valami figyelmeztetést adjon, de ne hibát jelezzen?
