### ISSUE TITLE
GDPR - Adatvédelmi szabályzat

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#264]
[Tájékoztató1](https://7blog.hu/gdpr/), [Tájékoztató2](https://itcafe.hu/hir/hetpecset_gdpr.html)
[Minta doksi](http://bkik.hu/wp-content/uploads/2018/04/Adatkezel%C3%A9si-t%C3%A1j%C3%A9koztat%C3%B3.pdf)
[Google Analytics](http://www.blastam.com/blog/5-actionable-steps-gdpr-compliance-google-analytics)

### Teendők:
- [x] cookie-sáv elhelyezése
- [x] Adatvédelmi szabályzat kitöltése és elhelyezése a honlapon
- [x] Google Analytics és Raven JS csak anonyme adatokat gyűjtsenek
- [x] cookie-sávban gomb javítása:

![image](https://user-images.githubusercontent.com/13850825/40317683-7d8d4848-5d22-11e8-88a7-1d6a1637cd07.png)

**Comment by maxinteger** [comment]
@zsebtanar szerintem a google analytics dolgot vegyük külön feladatba, főleg mert még utána kell járnom, hogyan is működik.
Az utolsó két ponttal kell még valamit csinálni?

**Comment by zsebtanar** [comment]
@maxinteger ok. igen, az utolsó ponttal mindenképp kell valami, mert a két gomb továbbra is összecsúszik. a felhasználóbarát leírással kapcsolatban is lehetne valamit kezdeni, bár elsősorban itt a törvényi megfelelés a cél.

**Comment by maxinteger** [comment]
Szerintem ezt lezárhatjuk, a következő feladat az lesz amikor már célzottan is szeretnénk követni a felasználókat.
