### ISSUE TITLE
Nem létező ID-jú (törölt) feladatok kezelése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#27]
Ha egy nem létező ID-jú feladat linkjére kattintok (pl. [ez](https://zsebtanar-proto-76083.firebaseapp.com/exercise/view/-KoxPZxP4KiRd_9h5TvJ), "loading..."-ot ír ki:
![image](https://user-images.githubusercontent.com/13850825/28231666-f8a7f044-68ec-11e7-9c79-fa8ca5da0c8d.png)

**Comment by zsebtanar** [comment]
és a feladatok is eltűntek (bár ez lehet, h más miatt van):
![image](https://user-images.githubusercontent.com/13850825/28231688-164c1490-68ed-11e7-9232-2a4c5b297fe9.png)

**Comment by zsebtanar** [comment]
így most ha rákattintok a linkre, üres képernyőt kapok. esetleg meg lehet oldani, hogy egy 404-es hibaüzenetet kapjak, és utána pedig egy átirányítást a kezdőlapra (mint a https://zsebtanar-proto-76083.firebaseapp.com/exercise esetében)?
![image](https://user-images.githubusercontent.com/13850825/28264283-85ff9a10-6aea-11e7-9189-79ac21108b1f.png)

**Comment by maxinteger** [comment]
Jelenleg ez a helyes működés. Előbb be kell jelentkezned majd, ennek hatására átkerüsz az admin oldalra és onna már elérhetőek a feladatok:
https://zsebtanar-proto-76083.firebaseapp.com/admin/exercise

Kérlek zárd le a feldatot, hogy nincs más probléma

**Comment by zsebtanar** [comment]
@maxinteger a probléma sztem az, hogy ha vmi érvénytelen linket írsz be, üres képenyőt kapsz. pl. ha ezt a linket, amit küldtél, külön megnyitom egy új fülön, akkor is üres képernyőt kapok, még akkor is, ha amúgy be vagyok jelentkezve. nem tudom, hogy ez mennyire tekinthető bug-nak, de mindenképpen fog kellemetlenségeket okozni a felhasználóknak. sztem a legjobb megoldás lenne, ha érvénytelen linkeknél automatikus átirányítás lenne a kezdőlapra. te mit gondolsz?

**Comment by maxinteger** [comment]
@zsebtanar Igaz, amit lerítál az #29 -es hibajegyben már szerepel, valószínűleg előbb azt fogom javítani. Egyenlőre az a megoldás, hogy kijelentkezel majd újra ba és csak a gombok segítsgével nagiválsz (ne tölsd újra az oldalt stb. )

**Comment by zsebtanar** [comment]
@maxinteger rendben.

**Comment by maxinteger** [comment]
@zsebtanar A 29-essel együtt ez is javítva lett (ha minden igaz)
