### ISSUE TITLE
Alapértelmezett megoldások elmentése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#274]
### Elvárt viselkedés
Ha egy beviteli mezőben vannak alapértelmezett értékek, akkor azokat mentse el a rendszer.

### Jelenlegi viselkedés
Nem menti el.

### Környezet
- szerver: test
- böngésző név és verzió: Chromium 65.0.3325.181
- OS: Ubuntu 16.04

### Lépések a viselkedés reprodukálásához
1. Hozz létre egy részfeladatot
2. Adj hozzá egy törtszám beviteli mezőt
3. Ha nem módosítod a számláló és a nevező értékét (alapértelmezett érték 1), és úgy mented el a feladatot, akkor az adatbázisban nem jelenik meg az eredmény.

**Comment by maxinteger** [comment]
@zsebtanar talán jobb lenne ha nem is lenne alapértelmezett értéke a mezőnek, a félreértések elkerülése végett

**Comment by zsebtanar** [comment]
@maxinteger rendben, ez jó ötlet.
