### ISSUE TITLE
Tizedestört engedélyezése közönséges törtben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#287]
### Elvárt viselkedés
Ha a felhasználó nem azt írja be, hogy 10/6, hanem hogy 1/0,6 azt is fogadja el a rendszer.

### Jelenlegi viselkedés
Csak egész számokat fogad el, különben figyelmeztet a rendszer.

### Környezet
 - szerver: prod

### Lépések a viselkedés reprodukálásához
L. ennek a feladatnak az első részfeladatát:
https://zsebtanar-prod.firebaseapp.com/exercise/-LBaAB9RvQpHiETKvk8A

**Comment by maxinteger** [comment]
Ezt már megvitattunk az előző megbeszélésen. A törtmezőbe egyik mezőjébe sem lehet beírni tizedes törtet. A kapcsolótó PR javítja ezt
