### ISSUE TITLE
Tizedestört beírása közönséges törtnél

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#288]
### Elvárt viselkedés
Ha a felhasználó véletlenül tizedestörtet ír a közönséges törtmezőbe, kap figyelmeztetést, és utána kijavítja, a rendszer fogadja el a megoldást.

### Jelenlegi viselkedés
Ha beírok tizedestörtet, utána már csak tizedestörtet fogad el.

### Környezet
 - szerver: prod
 - Chrome
 - Windows 7

### Lépések a viselkedés reprodukálásához
1) Nyisd meg ezt a feladatot: https://zsebtanar-prod.firebaseapp.com/exercise/-LBaAB9RvQpHiETKvk8A
2) Az első részfeladanál írj be a számlálóba 1-et, a nevezőbe 0,6-ot (ekkor hibát kapsz elvileg)
3) Most javítsd ki az 1-est 10-re, és a 0,6-ot 6-osra (továbbra is hibát kapsz)
![image](https://user-images.githubusercontent.com/13850825/43424117-a0e00746-944e-11e8-8cc2-181d2aab66c5.png)

**Comment by maxinteger** [comment]
Lásd #287 feladatot és a #293 PR-t
