### ISSUE TITLE
Facebook regisztráció nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#290]
### Elvárt viselkedés
Facebook fiókkal is lehessen regisztrálni.

### Jelenlegi viselkedés
Nem lehet.

### Környezet
 - szerver: prod

**Comment by maxinteger** [comment]
@zsebtanar Elvileg javítottam test-en és prod-on, próbáld ki te is és ha működik akkor zárd le a feladatot.
Köszi

**Comment by zsebtanar** [comment]
@maxinteger néztem, és sem test-en, sem prod-on nem működik továbbra sem.

**Comment by zsebtanar** [comment]
@maxinteger ezzel kapcsolatban van valami előrelépés/tudok valamiben segíteni?

**Comment by maxinteger** [comment]
@zsebtanar szerintem megtaláltam a hibát.

Nekem csak Firefoxban nem sikerült belépni, Chrome-ban működött minden esetben.
A Firefox esetében egy beépített plugin okozta a problémát. Ez a plugin leválasztja a Facebook oldalt a többitől ami nagyon jó, de sajnos a bejelentkezést is megakadályozta. A pluginnak van már újabb verziója amivel rendesen megy a bejelentkezés. Ehhez a következő kell tenni:

1) nyisd meg ezt az oldalt Firefox-ban https://testpilot.firefox.com/experiments/containers
2) Bal oldalon kell lennie egy piros gombnak "Containers kikapcsolása" felirattal
3) katt a gombra, majd a megerősítésre és kész

Ha még is kellene a plugin (erősen ajánlott) akkor innen lehet telepíteni a javított változatot
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by zsebtanar** [comment]
@maxinteger köszi, hogy utánanéztél. két kérdés:

1) ha jól értem, akkor ahhoz, hogy a felhasználó tudjon regisztrálni fb-kal, neki kell telepíteni/törölni valamit?
2) Chrome-ban még nem sikerült megoldani, hogy mi okozza a problémát, ugye?

**Comment by maxinteger** [comment]
@zsebtanar a Chrome-ra nem tudok mit mondani, mert azt nekem megy akkor is be vagyok lépve a Facebook-ba, de úgy is hogy ha a Zsebtanáron keresztül lépek be.
Javaslom kapcsold ki a pluginokat a böngésződben és próbáld újra. Ha megy akkor próbáld meg egyesével visszakapcsolni a pluginokat, hogy kiderüljön melyik okozza a gondot.
Ha így sem megy akkor a te gépeden kell kiderítenünk mi a baj.

**Comment by zsebtanar** [comment]
@maxinteger biztos, hogy a Chrome-on megy?

1) lépj ki a zsebtanárból
2) próbálj meg regisztrálni a fb fiókkal a zsebtanáron
3) jelentkezz be fb-ra
4) mi történik? (nekem bezáródik az ablak)

**Comment by zsebtanar** [comment]
@maxinteger letöltöttem a Chrome Canary-t és a Firefoxot. a Firefoxon követtem az utasításaid. egyiken sem sikerült belépni. ha már be vagyok lépve a fb-ra, akkor egyből eltűnik a bejelentkezési ablak, ha pedig nem, akkor megengedi, hogy bejelentkezzem, de amint ez megtörtént, ugyanúgy bezáródik az oldal. pontosan ugyanez történik a Chrome-ban is.

nemrég telepítettem az Avast-ot, szted ez bekavarhat?

**Comment by maxinteger** [comment]
@zsebtanar Szerintem az Avast nem kavarhat be kivéve ha van valami beépülő böngésző plugin-ja is. Bár így is kizártnak tartom, hogy pont a világ legnagyobb oldalát bejelentkező felületét blokkolná.

Én is teszteltem a belépést Linuxon, Windows-on, OSX-en, Firefox és Chrome böngészőkben, valamint Nóri is megnézte iOS safari-ban és mindegyik esetben működött.

Szóval kijelenthetjük, hogy általánosságban működik.

De érdemes kivizsgálni, hogy mi a gond a te gépeden, mert akár másnál is előfordulhat

**Comment by zsebtanar** [comment]
@maxinteger rendben, megnézhetjük valamikor.
