### ISSUE TITLE
Nem lehet email címmel regisztrálni

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#291]
*[Olvass el](./contribution.md#feladatletrehozas)*

### Elvárt viselkedés
Lehessen regisztrálni email címmel.

### Jelenlegi viselkedés
Nem lehet. A gomb nyomására nem történik semmi.

### Környezet
 - szerver: prod
 - Chrome
 - Windows 7

**Comment by maxinteger** [comment]
A #292 -es PR javítja ezt a problémát is
