### ISSUE TITLE
Kbd címke használata markdownban

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#297]
### Elvárt viselkedés
Ha számológéppel kapcsolatban írok infót, lehessen használni a `kbd` címkét:
![image](https://user-images.githubusercontent.com/13850825/43679543-dfcc76b6-9826-11e8-81c0-317f00aee1d6.png)

### Jelenlegi viselkedés
Csak a `code` funkciót tudom használni, amivel ezt kapom:
![image](https://user-images.githubusercontent.com/13850825/43679560-1e8b0db8-9827-11e8-8922-facae4318767.png)

**Comment by maxinteger** [comment]
Erre létezik markdown-it plugin

**Comment by ldorogi** [comment]
Akkor elkezdek vele foglalkozni ....

**Comment by maxinteger** [comment]
@ldorogi telepítettem a teszt szerveren, tökéletesen működik. Köszi.

**Comment by zsebtanar** [comment]
@ldorogi be tudnád írni a súgóba, hogy van ilyen funkció, és hogy hogy lehet használni?

@maxinteger nyissak erre új hibajegyet?
