### ISSUE TITLE
Bootstrap alert használata útmutatóknál

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#298]
### Elvárt viselkedés
Bootstrap alerteket is lehessen használni útmutatóknál (pl. azonosságokhoz, tételekhez):
![image](https://user-images.githubusercontent.com/13850825/43679594-b73b584c-9827-11e8-8990-3f5959177c3f.png)

### Jelenlegi viselkedés
Max félkövérrel való kiemelés lehetséges:
![image](https://user-images.githubusercontent.com/13850825/43679604-c52b4e26-9827-11e8-9eb6-08b20a5509d4.png)

**Comment by maxinteger** [comment]
@zsebtanar Szerintem az alert helyett jobb lenne a Wiki használata, két okból is:
1) a Wiki általánosabb koncepció és több helyen újra lehet hasznosítani
2) már így is túl sok szöveg van a képernyőn és nem csak mobil nézetben de laptopon is szinte kezelhetetlen. Tehát ahelyett, hogy újabb blokkal növeljük a tartalmat, inkább csak rakjuk egy linket wiki-re ami egy felugróban ablakban fogja mutatni.

**Comment by zsebtanar** [comment]
@maxinteger rendben
