### ISSUE TITLE
Navigálás feladatok között

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#299]
### Elvárt viselkedés
A felhasználó kényelmesen tudjon ugrálni a feladatok között. Pl:
![image](https://user-images.githubusercontent.com/13850825/43679792-dc8dc2de-982b-11e8-9fff-f7f20d9d0c6c.png)

### Jelenlegi viselkedés
Nincs ilyen funkció. A felhasználó csak a kezdőlapról választhat új feladatot.

**Comment by maxinteger** [comment]
@zsebtanar A feladatok között nincs semmilyen sorrendiség, maximum a létrehozás ideje, de jobb lenne ennél valamivel kifinomultabb módszert találni.

Várom a javaslatokat

**Comment by zsebtanar** [comment]
@maxinteger íme egy - nem túl profi, de kezdésnek jó - javaslat:
- előző feladat:
  - az azonos tantárgyhoz és témakörhöz tartozó feladatok közül az időrendi sorrendben előző
  - ha nincs ilyen, akkor az ábécérendben a témakör előtti témakör időben utoljára hozzáadott feladata
  - ha nincs ilyen, akkor kezdőlap
- következő feladat:
  - az azonos tantárgyhoz és témakörhöz tartozó feladatok közül az időrendi sorrendben következő
  - ha nincs ilyen, akkor az ábécérendben a témakör után következő témakör időben legelőször hozzáadott feladata
  - ha nincs ilyen, akkor kezdőlap

igazából a lényeg, hogy végig lehessen görgetni gyorsan minden feladaton anélkül egy fix sorrend mellett (ez azért jó, mert ha mégis tetszik a feladat, amit már ellapozott, könnyen visszatalál)

**Comment by maxinteger** [comment]
@zsebtanar A megbeszéltek szerint, ezt nem fogjuk lefejleszteni, viszont hasonló ötlet alapján fogjuk megcsinálni a #280 as feladatot
