### ISSUE TITLE
Lassú szerver válasz

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#300]
### Elvárt viselkedés
Az útmutatások ill. a megoldás ellenőrzése gyorsan (<1s) történjen.

### Jelenlegi viselkedés
Van, hogy 1 kattintásra >5s-ot kell várni, ami egy idő után eléggé rontja a felhasználói élményt.

### Környezet
 - szerver: prod
 - Chrome
 - Windows 7

**Comment by zsebtanar** [comment]
@maxinteger jól látom, jelen körülmények között egyelőre esélytelen <1 s alá szorítani a válaszidőt?

**Comment by maxinteger** [comment]
@zsebtanar Nekem úgy tűnik mintha javult volna a sebesség és csak az első lekérdezésnél kell várni 2-3 másodpercet. Ha te is így látod akkor lezárhatjuk ezt a feladatot

**Comment by zsebtanar** [comment]
Valamennyivel tényleg gyorsabb. Rendben, zárjuk le.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. aug. 22.,
Sze 0:09):
