### ISSUE TITLE
Hibaelhárítás oldal létrehozása

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#304]
Statikus oldal (mint a "rólunk" oldal) ahol gyakori problémák elhárítását írjuk le. Pl a Firefox Facebook bejelentkezés probléma

**Comment by zsebtanar** [comment]
@maxinteger nem lenne egyszerűbb, ha egyelőre letiltanánk a fb-os bejelentkezést?...

**Comment by maxinteger** [comment]
@zsebtanar Szerintem egy ilyen gyors segítség oldal mindig hasznos. Vannak olyan esetek amik csak néhány felhasználót érint és csak ők tudják javítani mert pl egy kiegészítő blokkolja a működést.

**Comment by zsebtanar** [comment]
@maxinteger rendben.
