### ISSUE TITLE
"Nehézség" metaadat hozzáadása

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#31]
Pl. ez a feladat elég nehéz (sok időt vesz igénybe): https://zsebtanar-proto-76083.firebaseapp.com/admin/exercise/view/-KpF8gEZyn7vG9QT7f-g. Jó lenne, ha ezt az admin oldalon meg lehetne adni.

**Comment by zsebtanar** [comment]
@maxinteger ez már a honlapon is elérhető? (még nem sikerült megtalálnom, hogy hol van)

**Comment by maxinteger** [comment]
@zsebtanar lehet elfelejtettem telepíteni :), este kirakom újra

**Comment by zsebtanar** [comment]
rendben, köszi :)
