### ISSUE TITLE
auto scroll a segítséghez

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#317]
### Elvárt viselkedés
Ha a felhasználó segítséget kér, akkor a segítséghez ugorjun a feladat (a választási opciók fölé)

### Jelenlegi viselkedés
[Ennél](https://zsebtanar-test.firebaseapp.com/exercise/-L9gQD0Zo7SvsQXBEcFh) a feladatnál túl magasak a választási opciók, így a megoldás nem látszik. (A hiba nem sok feladatot érint.)

### Környezet
 - szerver: test
 - Chrome
 - Windows

### Lépések a viselkedés reprodukálásához

 1) nyisd meg a feladatot
2) válaszd ki a 3. opciót (rossz)
3) kérj segítséget
4) a segítség nem látszódik

**Comment by maxinteger** [comment]
Kész (véletlenűl a develop-ba toltam be :D)
