### ISSUE TITLE
Hibás megoldás és megoldás útmutató

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#32]
https://zsebtanar-proto-76083.firebaseapp.com/admin/exercise/edit/-KpF9T6e90WnKuVPIyD3

A feladatleírásban 8dkg van de a megoldás és a megoldás útmutató is 10-el számol

**Comment by zsebtanar** [comment]
köszi, javítottam! (egyébként ha a linkre kattintok, itt is az admin oldalra irányít át, úgyhogy a listából kellett kikeresnem a feladatot - most még ~10 feladatnál ez mondjuk még így is megoldható).

**Comment by maxinteger** [comment]
@zsebtanar belefutottam én is, felvettem hibának #33

**Comment by zsebtanar** [comment]
köszi!
