### ISSUE TITLE
Reklám elhelyezése weboldalon?

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#321]
### Elvárt viselkedés
Érdemes lenne elgondolkozni azon, hogy hogyan tudjuk hosszútávon fenntarthatóvá tenni a projektet. Azt tuti nem szeretnénk, ha az app fizetős lenne (max a reklámmentes változat). Viszont szerintem a felhasználók tisztában vannak vele, hogy ingyenes appokban van reklám. A kérdés, hogy mennyi, és hol.

Nekem a Brain it on nevű játék stratégiája nagyon tetszik (bár vannak felhasználók, akik bírálják). Az app ingyenesen letölthető [itt](https://play.google.com/store/apps/details?id=com.orbital.brainiton&hl=en_GB). Van reklámmentes, prémium változata. Az appban két helyen van reklám:
- Megoldott feladatok után (nem mindig) - ezeket általában ki lehet kattintani
- Súgók mutatása előtt (ezek általában videók, sőt van, hogy végig kell várni a 30s-ot, ami sztem nem szerencsés)

Szerintem mi is elgondolkozhatunk azon, hogy 1-1 megoldott feladat/küldetés után berakunk 1 reklámot. Talán a súgóknál a reklám idegesítőbb - de 1-1 sikeres feladat után az ember alapból nyugodtabb picit. @maxinteger Te mit gondolsz?

**Comment by zsebtanar** [comment]
Példa: a duolingonál így tálalják a reklámokat:

![image](https://user-images.githubusercontent.com/13850825/44345332-551e5880-a493-11e8-9938-f3c1f3a42c96.png)

**Comment by maxinteger** [comment]
@zsebtanar ha te is egyetértesz velem akkor szerintem
- nem szabad, hogy megzavarja a feladatmegoldást, ezért inkább a nyitóoldalon és a keresőben tudom elképzelni a reklámokat
- szerintem egy évig még ki tudjuk húzni és addigra talán bejönnek az alternatív támogatási formák (1%, paypal, Patreon)
szóval egyenlőre záruk le ezt a feladatot

**Comment by zsebtanar** [comment]
@maxinteger ok
