### ISSUE TITLE
Pontrendszer / küldetések

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#323]
### Elvárt viselkedés
A felhasználók bizonyos küldetéseket/feladatokat csak bizonyos feltételekkel tudjanak megnyitni.

Példa: Brain it on:

- összesen 240 feladat van, ami 12 db egyre nehezedő, 20 db-ból álló feladatcsomagra van szétbontva
- először csak az első csomagot látod, a többi zárva van
- minden megoldott feladatért 1, 2 vagy 3 csillagot kapsz, ezek a képernyő tetején gyűlnek
- minden csomagnak van egy "ára", azaz el kell érni egy bizonyos számú csillagot ahhoz, hogy fel tudd oldani őket

![image](https://user-images.githubusercontent.com/13850825/44345855-babf1480-a494-11e8-939e-bc100a79cabe.png)

![image](https://user-images.githubusercontent.com/13850825/44345862-bf83c880-a494-11e8-9852-10ca81764aef.png)

**Comment by maxinteger** [comment]
@zsebtanar mivel azt beszéltük, hogy a wiki-n folytatjuk ezért létrehoztam az oldalt és ezt a feladatot most lezárom. Ha gondolod másold mát a fenti példát is a wiki oldalra

https://github.com/zsebtanar/zsebtanar-proto/wiki/Tervezet---Pontrendszer-%C3%A9s-k%C3%BCdet%C3%A9sek
