### ISSUE TITLE
Patreon adomány app integrálása

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#324]
A Patreon egy mikro-adomány oldal amin keresztűl bárki segíthet egy kisüsszegű de havi rendszerességű adománnyal

https://www.patreon.com

- [x] A Zsebtanár megfelel az oldal kritériumainak
- [x] Nekünk megfelelnek az oldal feltételei (pl mennyit vonnak le, mikor utalnak, stb.)
- [x] Hogyan tudunk ezzel elszámolni mint alapítvány (ugya az mitn a paypal?)
- [x] Integráció az oldalra ha minden OK
- [x] Settings / Payout preferences átnézése

**Comment by zsebtanar** [comment]
@maxinteger sikerült regisztrálni. a paypalt nem tudtam integrálni, mivel nincs kártya, viszont úgy látom, küldeni már így is lehet.
