### ISSUE TITLE
Rólunk oldal frissítése

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#325]
- [x] Oldal tartalmának átnézése, szükség esetén frissítése
- [x] Valahogy személyesebbé kellene tenni a "Kik állnak mögötte?" részt
- [x] Az oldal kiadásairól is írhatnánk itt.
- [x] adományozási lehetőségek hozzáadása
- [x] Elérhetőségek hozzáadása:
   - facebook oldal címe
   - email cím (?)
   - visszajelzés gomb

**Comment by zsebtanar** [comment]
@maxinteger a másodikkal kapcsolatban mit szólnál, ha lenne egy közös fénykép pl. az, amit legutóbb a Margit-szigeten készítettünk?
