### ISSUE TITLE
Részfeladatok elrejtése megoldás közben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#354]
### Elvárt viselkedés

Bizonyos feladatok megoldásánál a felhasználó mindig csak az aktuális részfeladatot lássa, az előzőeket ne.

Így a feladatkészítők létrehozhatnak "kvázi-véletlenszerű" feladatokat (minden részfeladat ugyanaz, csak más számokkal) anélkül, hogy komolyabban bele kellene nyúlni a rendszerbe.

### Jelenlegi viselkedés

Minden részfeladat látszik.

![image](https://user-images.githubusercontent.com/13850825/46907951-590eaa00-cf1b-11e8-8e49-9463e4be1d3a.png)

**Comment by maxinteger** [comment]
@zsebtanar kitudod fejteni kicsit bővebben a feladatleírásban miért van erre szükség?

**Comment by zsebtanar** [comment]
@maxinteger így jó?

**Comment by maxinteger** [comment]
@zsebtanar Ha jól értem akkor ez egyfajta meg hackelése a rendszernek az által, hogy egy feladatba erőltetünk bele több feladatot a részfeladatokon keresztül.

Ez a megközelítés teljesen rossz, mert 
 - így kezelhetetlenné válnak a feladatok az admin oldalon, 
 - nem lehet véletlenszerűen egymás után fűzni feladatokat, mert fixen be van írva a sorrend a feladatba
 - a feladat elveszíti eredeti definícióját mert bizonyos esetekben egy összetett feladatot jelöl máskor meg egy halom kis feladatot.

Szerintem erre egy teljesen új funkció kell ami lehetővé teszi feladatlisták létrehozását és szerintem a #23  pont erről szól.

**Comment by zsebtanar** [comment]
Rendben, más alternatívára is nyitott vagyok. Ha szerinted ez jó, akkor
nyugodtan zárd le ezt a feladatot.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. okt. 13.,
Szo 20:10):

**Comment by zsebtanar** [comment]
a végső cél az automatikusan generált feladatok lennének, de mivel ez elég
nagy projekt, jó lenne egy olyan "félautomata" megoldás, amiben már
tesztelhetnénk ilyen típusú feladatokat (azaz, ugyanaz a feladat csak más
számokkal). igazad van, a feladatsorok erre valóban alkalmasak, úgyhogy
lezárhatjuk ezt a feladatot.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. okt. 13.,
Szo, 21:25):

**Comment by maxinteger** [comment]
@zsebtanar köszi így már világos :)
Szerintem a feladatsor feladat nem olyan vészes, szóval így is úgy is szükség lesz rá szóval előrébb veszem
