### ISSUE TITLE
Facebook regisztráció segítségkérés közben nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#355]
### Elvárt viselkedés
Segítségkérés közben is lehessen regisztrálni/bejelentkezni

### Jelenlegi viselkedés
Ha segítséget kérsz, és utána akarsz regisztrálni, eltűnik a modal, de csak a feladatot látod, nem a regisztrációs felületet

### Környezet
 - szerver: prod
 - böngésző név és verzió: Chrome
 - Windows 7

### Lépések a viselkedés reprodukálásához

1) nincs meg ezt a feladatot: https://zsebtanar.hu/exercise/-LBaAB9RvQpHiETKvk8A
2) kattints az "ellenőrzés" gombra (a megoldási mezőt hagyd üresen)
3) kattints a "kérek segítséget" gombra
4) regisztrálj fb-kal a gomb segítségével

**Comment by maxinteger** [comment]
@zsebtanar Nem tudtam reprodukálni a problémát. Simán be tudtam jelentkezni Facebook feladatmegoldás közben úgy hogy nem vesztettem el a beviteli mezők tartalmát sem.

Nem lehetséges, hogy az általad leír probléma a #310 miatt van?

**Comment by zsebtanar** [comment]
Lehetséges.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. okt. 28.,
V 20:06):
