### ISSUE TITLE
Újonnan hozzáadott feladat nem töltődik be a test szerveren, publikus nézetben

### ISSUE THREAD

**Issue by szape** [zsebtanar/zsebtanar-proto#363]
### Probléma leírása
A test szerveren készítettem egy új feladatot (#18, "Legkönnyebb egyenlet"). Aktiváltam is, hozzáadtam az "Egyenletek" témakörhöz. Amikor a publikus oldalon rámegyek az "Egyenletek" linkre, megjelenik a "kis türelmet" felirat a forgó fogaskerékkel, és nem történik semmi (nagyon hosszú ideig vártam rá, inkognitóablakban is próbáltam). A többi témakör feladatai rendben bejönnek. Ugyanez tapasztalható, ha nem témakör, hanem osztály szerint akarom megtekinteni a feladatot (9. osztály).
Ha az Admin felületen archiválom a feladatot, akkor Public-on újbúl rendesen betölt minden lap, csak a kérdéses feladat nem jelenik meg.

### Környezet
 - szerver: test
 - böngésző név és verzió: Google Chrome 69.0.3497.100 (64 bites), Firefox 63.0 (64 bites)
 - OS név és verzió: Windows 8

**Comment by maxinteger** [comment]
@szape Köszönöm a hibabejelentést.

Valóban, a feladat valami oknál fogva nem került át a publikus adat "táblába" viszont az összes metaadat és kereső tartalmazza, ezért van az, hogy a kategória link már látható, de a feladat nem töltődik be.
A konzolban látható is a hiba "A kért feladat nem létezik"

Igyekszem mihamarabb javítani

**Comment by maxinteger** [comment]
@szape Javítottam a hibát, működik a mentés és elérhető a feladatod a publikus oldalon.

Lezárom a feladatot, de ha továbbra is jelentkezik a fenti probléma akkor nyugodtan írj ide és újranyitom.

**Comment by szape** [comment]
Köszi :)
