### ISSUE TITLE
Kulcsszavak & találatok mentése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#368]
Amikor a felhasználó rákeres egy kulcsszóra, küldjük el a Google Analyticsnek a találatok számával együtt. Így fel tudjuk mérni, hogy mely témakörök hiányoznak a rendszerből.

**Comment by maxinteger** [comment]
@leslie-magnafuzz köszi a PR-et, kód és a beküldött adat is jó, már csak kell valaki aki ért az Analytics adminhoz, hogy valami értelmezhető riport legyen belőle.
