### ISSUE TITLE
Google belépés nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#374]
### Jelenlegi viselkedés
Nem lehet Google-lal belépni. A felugró ablak néhány másodperc múlva bezár.

### Környezet

 - szerver: prod
 - böngésző: Chrome
 - OS: win 7

### Lépések a viselkedés reprodukálásához

 1) nyisd meg a https://zsebtanar-prod.firebaseapp.com/ oldalt
2) kattints a Belépés -> Google fiókkal menüpontra

**Comment by maxinteger** [comment]
@zsebtanar nekem nem sikerül reprodukálni a hibát, Google és Facebook fiókkal is be tudtam jelentkezni.
Igazán és a https://zsebtanar.hu -t próbáltam és nem a https://zsebtanar-prod.firebaseapp.com/ címet
Jobb ha az új címet használod

**Comment by zsebtanar** [comment]
@maxinteger köszi a jelzést. a zsebtanar.hu-n nekem is működik. lezárhatjuk.
