### ISSUE TITLE
"Sikeres bejelentkezés" felirat oldal frissítéskor

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#376]
### Elvárt viselkedés
A felhasználó csak ki/bejelentkezéskor kapjon értesítést arról, hogy be van-e jelentkezve vagy nem.

### Jelenlegi viselkedés
Minden frissítéskor megjelenik egy zöld modal. Ráadásul még a feladatot is eltakarja:
![image](https://user-images.githubusercontent.com/13850825/51863541-97e93400-2341-11e9-8d83-9c95c3e2500f.png)

### Környezet

 - szerver: test/prod
 - böngésző: Chrome
 - OS: win7

### Lépések a viselkedés reprodukálásához

1) jelentkezz be a teszt szerverre
2) nyisd meg ezt: https://zsebtanar-test.firebaseapp.com/exercise/-LAyPiYyRAsZFwb-8K41
3) frissítsd az oldalt

**Comment by maxinteger** [comment]
No reproducible
