### ISSUE TITLE
Feladat bezárása nem működik (test+prod)

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#380]
Az alábbi feladatot nem lehet bezárni a (w7, chrome) - az "X" gomb nem működik:
- teszt: https://zsebtanar-test.firebaseapp.com/exercise/-LWwAdU53xIGvlAiUuMe
- prod: https://zsebtanar.hu/exercise/-L9qaEOnx1tk3P6VV1gt

**Comment by maxinteger** [comment]
Csak akkor nem működik ha közvetlenül nyitod meg a feladat oldat, de ha pl a feladat kategóriából jössz akkor viszont működik.

az X lényegében egy vissza gomb

**Comment by zsebtanar** [comment]
@maxinteger lehetne ezen változtatni? vagy pl. ilyenkor lehetne a kezdőlapra visszairányítani a felhasználót?

**Comment by maxinteger** [comment]
@zsebtanar javítottam, elvileg teszten már működik
