### ISSUE TITLE
Figyelmeztetés nem jelentik számlistánál

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#382]
### Elvárt viselkedés
A számlistánál is jelenjen meg figyelmeztetés, hogy hány tizedesjegy pontossággal kell számolni:
![image](https://user-images.githubusercontent.com/13850825/51945313-a8231100-241e-11e9-80ab-0ba4a07f2f0f.png)

### Jelenlegi viselkedés
Nem jelenik meg:
![image](https://user-images.githubusercontent.com/13850825/51945413-00f2a980-241f-11e9-854b-a673b64a0404.png)

### Környezet
 - szerver: test
 - böngésző név és verzió: chrome
 - OS név és verzió: w7

### Lépések a viselkedés reprodukálásához
https://zsebtanar-test.firebaseapp.com/exercise/-LXQkjo5UizSczjG1W-i

**Comment by leslie-magnafuzz** [comment]
Ezt magamra vállalom.

**Comment by zsebtanar** [comment]
@leslie-magnafuzz köszi!

**Comment by vektor8891** [comment]
@co-NaN @maxinteger van már esetleg ETA a javításra?

**Comment by co-NaN** [comment]
@vektor8891 Én részemről megvagyok, ha erre gondolsz.,

**Comment by vektor8891** [comment]
@co-NaN Köszi az infót! Írtam @maxinteger-nek, hogy fogadja el a PR-t, ha nincs kifogása. :)

**Comment by maxinteger** [comment]
@co-NaN Elnézész, nem láttam az utolsó commit-ot.

Este ránézek és ha minden ok, akkor lezárom

**Comment by maxinteger** [comment]
Ellenőriztem és minden OK.

 @co-NaN Köszi, hogy javítottad a hibát :)

**Comment by co-NaN** [comment]
@maxinteger Szuper! Nm. :)
