### ISSUE TITLE
Teszt szerver nem elérhető

### ISSUE THREAD

**Issue by szape** [zsebtanar/zsebtanar-proto#386]
Nem megy a teszt szerver. Rá tudna valaki nézni?

**Comment by maxinteger** [comment]
Tudunk róla, már jeleztem a Google-nek
Jelezni fogom ha megoldódott.

**Comment by maxinteger** [comment]
Firebase support szerint cache header van rosszul beállítva...

**Comment by szape** [comment]
Köszi, akkor várom, hogy megjavuljon.

Peti

László Vadász <notifications@github.com> ezt írta (időpont: 2019. febr. 2.,
Szo, 23:39):

**Comment by maxinteger** [comment]
Megtalálták a hibát. A config.json fájlban `ḥ` volt `h` helyett.

**Comment by maxinteger** [comment]
@szape hiba elhárítva

**Comment by szape** [comment]
Szuper! Nem csoda akkor, hogy szemre nem látszott a hiba. Azt a kis pöttyöt
a "h" alatt könnyű valami piszoknak nézni :)
Köszi még egyszer!

Peti

László Vadász <notifications@github.com> ezt írta (időpont: 2019. febr. 7.,
Cs, 20:05):
