### ISSUE TITLE
Drag&drop nem működik (PROD)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#387]
### Elvárt viselkedés
Útmutatókat lehessen mozgatni.

### Jelenlegi viselkedés
A "drag"-ig működik a dolog, azaz mozgatni lehet. Mozgatás után a kártyák eltűnnek egy ideig, de a többi kártya sorrendje nem változik meg:
![image](https://user-images.githubusercontent.com/38993315/52301654-35b8b080-298b-11e9-8334-29b9b06bd312.png)

### Környezet

 - szerver: prod
 - böngésző: chrome
 - OS: win7

### Lépések a viselkedés reprodukálásához

 1) hozz létre egy feladatot
 2) hozz létre egy részfeladatot
 3) próbálj meg több útmutatót létrehozni, és mozgatni őket.

**Comment by maxinteger** [comment]
Javítva
