### ISSUE TITLE
Oldal átirányítása feladat mentése után

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#388]
### Elvárt viselkedés
Miután a feladatot elmentem, ugyanott maradjak, hogy tudjam egyből aktiválni is.

### Jelenlegi viselkedés
A mentés után az admin főoldalra irányít a honlap, ahonnan ismét ki kell keresni a megfelelő feladatot:

![image](https://user-images.githubusercontent.com/38993315/52302275-f3906e80-298c-11e9-8e89-fd724c5e69f8.png)

![image](https://user-images.githubusercontent.com/38993315/52302247-da87bd80-298c-11e9-9616-430d6b9bb62b.png)

### Környezet

 - szerver: prod
 - böngésző: Chrome
 - OS: win7

### Lépések a viselkedés reprodukálásához

 1) hozz létre egy úgy feladatot
 2) mentsd el

**Comment by maxinteger** [comment]
Javítottam a hibát.
Viszont ha új feladatot hozol létre és elmented akkor újra fog töltődni az oldal, viszont nem ugrik vissza a főoldalra

**Comment by vektor8891** [comment]
Rendben, ez így jó lesz. Köszi!

László Vadász <notifications@github.com> ezt írta (időpont: 2019. febr. 7.,
Cs 22:01):
