### ISSUE TITLE
Keresés kiterjesztése osztályokra

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#391]
### Elvárt viselkedés
Ha a keresőmezőbe valaki azt írja be, hogy "8. osztály", akkor kidobja a 8. osztályos feladatokat.

### Jelenlegi viselkedés
1 db 9. osztályos feladatot kapok teszt szerveren:
![image](https://user-images.githubusercontent.com/38993315/52593462-4ebcd800-2e49-11e9-8070-d686544f07e2.png)

### Környezet
test/Chrome/win7

**Comment by maxinteger** [comment]
@vektor8891 
Csak a kereső motor beállításait kellett módosítani, most már jó a teszt és az éles szerveren is

A keresési prioritás a következő:
- description
- tags
- grade
- topic
- subject
- difficulty

ha valami nem megy rendesen akkor kérlek nyisd újra a feladatot
