### ISSUE TITLE
Direkt admin link nem működik

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#393]
### Elvárt viselkedés
Ha pl. beírom, hogy https://zsebtanar.hu/admin/exercise/edit/-L8MUv7TvI1_ILnGRbOa, akkor vigyen át az adott feladat szerkesztőfelületére.

### Jelenlegi viselkedés
Átirányít az https://zsebtanar.hu/admin/ oldalra.

### Környezet
 - szerver: prod
 - böngésző: chrome
 - OS: win7

**Comment by maxinteger** [comment]
@vektor8891 
Légyszi nézd meg Teszt-en is, mert szerintem ezt már javítottam.
