### ISSUE TITLE
Tizedesjegyek száma a megoldásmezőben

### ISSUE THREAD

**Issue by szape** [zsebtanar/zsebtanar-proto#395]
Volt némi problémám a tizedestörtes megoldásokkal a tesztszerveren. Sikerült valamennyire lenyomoznom a jelenséget, melyet az alábbi két feladattal szemléltetek:
I.) https://zsebtanar-test.firebaseapp.com/exercise/-LZP1X_l7QXjU3VaSNGO
II.) https://zsebtanar-test.firebaseapp.com/exercise/-LZPF8SYJ7fK39PgHFlR

Mindkét feladatnak 1 részfeladata van 2 megoldásmezővel, és 2 tizedesjegy pontosággal kérjük a megoldásokat. A megoldások a=0, b=0,05.
A különbség annyi hogy az I. feladat leírásánál az első megoldásmezőhöz "0" van megadva megoldásnak a II. feladatnál pedig "0,00".

Az I. feladat elfogadja az a=0-t de hibás megoldásnak jelzi az a=0,00-t. A II. feladat pont fordítva. Ezzel az a baj, hogy mindkettőt jó megoldásnak kellene elfogadnunk (a 0,0-ról nem is bezélve). Másrészt a feladat készítője is könnyen megszívathatja magát ezzel, és azt hiheti, hogy valamilyen más issue miatt nem működik a feladat.

Meg lehetne azt oldani valahogy, hogy a különböző számformátumok egységesen legyenek kezelve?

**Comment by maxinteger** [comment]
@szape 
Javítottam a hibát, kérlek próbáld ki a teszt környezetben és ha valami hibát találsz akkor nyisd újra a feladatot, addig is lezárom :)

**Comment by vektor8891** [comment]
@szape meg tudnád nézni, hogy működik-e?

**Comment by szape** [comment]
Köszi! Megnézem, működik-e.

Peti

vektor8891 <notifications@github.com> ezt írta (időpont: 2019. ápr. 17.,
Sze, 4:35):

**Comment by szape** [comment]
Leellenőriztem, tökéletesen működik! :)

Peti

Szabó Péter <nemderogatorius@gmail.com> ezt írta (időpont: 2019. ápr. 17.,
Sze, 8:14):
