### ISSUE TITLE
Magyarosítás

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#4]
- [x] "tag" helyett "címke"
- [x] "segítség markdownhoz" helyett "útmutató szerkesztéshez" (a markdownt nem igazán ismerik)
- [x] "prefix" -> "előtag"
- [x] "postfix" -> "utótag"
- [x] "beviteli mezők" -> megoldás
- [x] tippek -> megoldási útmutató(?)
- [x] "Szőközök figyelmenkívűl hagyása" -> "Szóközök figyelmen kívül hagyása"

**Comment by maxinteger** [comment]
@zsebtanar a 3-at nem értem hogyan kapcsolódik a magyarításhoz

**Comment by zsebtanar** [comment]
@maxinteger jogos :)

**Comment by zsebtanar** [comment]
ez lehet magyarosítani?
![image](https://user-images.githubusercontent.com/13850825/28644460-f7f100ac-7259-11e7-9e48-d4642d25e755.png)

**Comment by zsebtanar** [comment]
+1 javaslat:
- [ ] bejelentkezésnél "hasz**á**náld email címed" helyett "használd **az** email címed"
![image](https://user-images.githubusercontent.com/13850825/28644477-088d95e2-725a-11e7-8414-348f4c61b561.png)

**Comment by maxinteger** [comment]
@zsebtanar Mindent lehet ;)
és köszönöm a javaslatot, kicsit késő volt amikor ezt írtam...

**Comment by zsebtanar** [comment]
@maxinteger semmi gond, velem is megesik :)

**Comment by maxinteger** [comment]
Javítottam

**Comment by zsebtanar** [comment]
@maxinteger a regisztrációnál át lehet írni a "bejelentkezést" arra, hogy "regisztráció google-lel/fb-kal/email-lel" stb?

![image](https://user-images.githubusercontent.com/13850825/29244546-4f085ad8-7f80-11e7-9095-9443c04cab20.png)

**Comment by maxinteger** [comment]
@zsebtanar javítottam
