### ISSUE TITLE
Profil link magyarosítás

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#407]
### Elvárt viselkedés

Profil ikonnál a legördülő menüben magyar szó legyen (pl. Profil/Fiókom stb.)

### Jelenlegi viselkedés
![image](https://user-images.githubusercontent.com/38993315/56257004-e1bbfd80-6098-11e9-96ce-9b2fe3c77d53.png)

### Környezet

 - szerver: prod
 - böngésző név és verzió: Chrome 11
 - OS: W7

**Comment by maxinteger** [comment]
Kész
