### ISSUE TITLE
Ábrák nem jelennek meg előnézetben (PROD)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#409]
### Elvárt viselkedés

Ábrák is megjelenjenek előnézetben.

### Jelenlegi viselkedés

Nem jelennek meg:

![image](https://user-images.githubusercontent.com/38993315/56334646-3168fa80-6167-11e9-9a4d-bd453f46bdb9.png)

### Környezet

 - szerver: prod
 - böngésző: chrome 11
 - OS: win7

### Lépések a viselkedés reprodukálásához

   https://zsebtanar.hu/admin/exercise/edit/-LE_BoSAWcia3SKFObU6#

**Comment by maxinteger** [comment]
Done
