### ISSUE TITLE
Útmutató nem jelenik meg előnézetben

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#410]
### Elvárt viselkedés

Útmutatók is megjelenjenek előnézetben.

### Jelenlegi viselkedés

Nem jelennek meg:

![image](https://user-images.githubusercontent.com/38993315/56335160-68401000-6169-11e9-96d6-6592628264ed.png)

### Környezet

 - szerver: prod
 - böngésző: Chrome 11
 - OS: win 7

### Lépések a viselkedés reprodukálásához

https://zsebtanar.hu/admin/exercise/edit/-LE_PqYRnK38Kyvqw0v4

**Comment by maxinteger** [comment]
Won't do
