### ISSUE TITLE
Feladatok számának megjelenítése témaköröknél

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#417]
### Elvárt viselkedés

A kezdőlapon minden témakör mellett egy kis jelvényben legyen látható, hogy az adott témakörhöz hány feladat tartozik.

### Jelenlegi viselkedés

Jelenleg nincs ilyen funkció.

**Comment by maxinteger** [comment]
@vektor8891 
Kicsit gondolkodtam ezen a feladaton és nem igazán látom a gyakorlati hasznát, nem hiszem, hogy bárki is az alapján válasz feladatot, hogy melyik kategóriában mennyi feladat van.
Illetve most realizáltam mennyi kategória van a nyitó oldalon, szerintem ennyi elemnél már zavaró lehet a sok szám és létisztultságot is rontja.

Több hasznát látom ha a kategória oldalon írjuk ki, hogy mennyi feladat érhető el.

Mit gondolsz?

**Comment by vektor8891** [comment]
@maxinteger "nem hiszem, hogy bárki is az alapján válasz feladatot, hogy melyik kategóriában mennyi feladat van" - én ezzel nem értek egyet. ha pl. az egyik kategóriában 1 feladat van, a másikban meg 100, sztem az utóbbira többen rá fognak kattintani (főleg, ha már a másikat megnézték egyszer). a letisztultság viszont jogos. úgyhogy legyen inkább, ahogy mondod: írjuk ki a kategória oldalon a feladatok számát.

**Comment by maxinteger** [comment]
@vektor8891 
"az egyik kategóriában 1 feladat van, a másikban meg 100" valóban, de ez egy probléma a feladat készítők oldalán is, mert ez azt is jelenti, hogy egyoldalúan kerülnek fel feladatok :)

Mivel témakörökről beszélünk ezért továbbra is úgy gondolom, hogy a témakör neve fontosabb a dönté szempontjából mint az, hogy mennyi feladat van benne... kivéve ha valaki véletlenszerűen ugrál, de arra meg ott a kereső

**Comment by vektor8891** [comment]
@maxinteger rendben, elfogadom a véleményed. sztem egyelőre hagyjuk ezt, aztán majd ha a felhasználóktól érkezik hasonló kérés, új témát nyitunk.
