### ISSUE TITLE
Kategória nem jelenik meg prodban!!! SOS

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#418]
Erre üres weboldalt kapok:

https://zsebtanar.hu/subject/-LA4J0N_CrzuVOjy0xyg/-LDrzVOLprc56AimcuJW

A többi kategória működik.

**Comment by maxinteger** [comment]
@vektor8891 A hibát javítottam és kitelepítettem az éles szerverre,
ha valami még sem jó akkor nyisd újra a feladatot

**Comment by vektor8891** [comment]
@maxinteger köszi a gyors inkézkedést!
