### ISSUE TITLE
Feladat link nem működik

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#424]
Keress rá arra, hogy "halmazelmélet", és az első találatra kattints rá:
![image](https://user-images.githubusercontent.com/38993315/57575598-66413800-741b-11e9-9f00-4c500b9b5334.png)

Nekem azt írja ki, hogy a feladat nem található.

Ez a feladat linkje: https://zsebtanar.hu/exercise/-LeUl4dtRnrHalHIveR1

**Comment by maxinteger** [comment]
@vektor8891 Most próbáltam ki és nekem működik, kérlek nézd meg te is újra.

**Comment by vektor8891** [comment]
@maxinteger most már tényleg jó, köszi!
