### ISSUE TITLE
Megváltozott tantárgy nem frissül

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#425]
Ennél a feladatnál: https://zsebtanar.hu/exercise/-LedEZKWj-LDIoOZBVJI megváltoztattam a tantárgyat "Felvételi (8.o)"-ról "Érettségi"-re, de a kezdőlapon még mindig a régi tantárgy alatt látszik.

![image](https://user-images.githubusercontent.com/38993315/57668035-f0340100-75d3-11e9-8fef-3dc940fc6af2.png)

![image](https://user-images.githubusercontent.com/38993315/57668052-08a41b80-75d4-11e9-9204-32e19ba04f12.png)

**Comment by maxinteger** [comment]
Done
