### ISSUE TITLE
Hibaüzenet feladat létrehozása közben

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#429]
Egyik feladat létrehozásakor ezt kaptam:
![image](https://user-images.githubusercontent.com/38993315/58677139-cba48c80-8328-11e9-8898-a7f818d7de8e.png)

Lehet, hogy az volt a baj, hogy nem adtam meg témakört, csak tantárgyat.

**Comment by maxinteger** [comment]
Done
