### ISSUE TITLE
\hline not working in Katex equation

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#432]
This:

```
$$\begin{aligned}
12&\\ 
+\,453&\\
\hline
\end{aligned}$$
```

Should produce something like this:

![image](https://user-images.githubusercontent.com/38993315/68178810-55e9c000-ff5b-11e9-91ba-8adabf0f6dc7.png)

But it doesn't render in prod in Chromium on Ubuntu 18.04

**Comment by vektor8891** [comment]
it works without `\hline`

**Comment by maxinteger** [comment]
Probably a library update can solve the problem

**Comment by vektor8891** [comment]
@maxinteger can we add this to the current project? i encountered similar problem.

**Comment by maxinteger** [comment]
@vektor8891 fixed
