### ISSUE TITLE
Bejelentkezés nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#44]
Nem tudok bejelentkezni a felhasználónév/jelszó párossal.

![image](https://user-images.githubusercontent.com/13850825/29097828-f4617c4a-7c69-11e7-9576-09fc8a541079.png)

**Comment by maxinteger** [comment]
@zsebtanar 
Úgy tűnik tegnap lehalt a telepítés és nem vettem észre azért nem volt kint sok módosítás sem.

Próbáld újra a bejelentkezést, nekem most működik

**Comment by zsebtanar** [comment]
@maxinteger a normál bejelentkezés továbbra sem működött a szaboviktor1988@gmail.com felhasználónévvel ill. 6K55pg6*Dk0w jelszóval. próbáltam a fb-os bejelentkezést, de ott a felugró ablak egy idő után eltűnt. a google-ös bejelentkezés végül sikeres volt.

**Comment by maxinteger** [comment]
@zsebtanar Remélem ezt a jelszót sehol máshol nem használod!

Este ránézek a problémákra, de egy valamit érdemes észben tartani, ha a google-s és az email-es regisztrációnál megegyezik az email cím akkor csak az egyiket tudod haszálni. A Facebook-os regisytrációt még nem is próbáltam eddig :)

Ha gondolod akkor törlöm a felhasználódat a DB-ből és újra tudsz regisztrálni (miután megbizonyosodtam, hogy amúgy a kód rendben van)

**Comment by zsebtanar** [comment]
@maxinteger nem, ez automatikusan generált jelszó. lehet, hogy a felhasználó törlése jó ötlet (még most sem működik).

**Comment by maxinteger** [comment]
@zsebtanar most töröltem a felhasználódat, szólj ha újra regisztráltál és akkor adok admin jogot

**Comment by zsebtanar** [comment]
@maxinteger regisztráltam.

**Comment by maxinteger** [comment]
@zsebtanar most már admin vagy, szólj ha még mindig nem megy

**Comment by zsebtanar** [comment]
@maxinteger működik minden, köszi szépen!
