### ISSUE TITLE
Add Youtube reference to the site

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#443]
- Add a new link to the footer which is pointing to the Zsebtaner's Youtube page
- Add Youtube to the home page

**Comment by vektor8891** [comment]
It would be great if time stamps would be also recognized, e.g.: https://youtu.be/7ATwDj0EX4Q?t=430

**Comment by maxinteger** [comment]
@vektor8891 
My plan is to embed the latest video from the youtube channel
In this case the time parameter is not applicable.

If we want to add the video to the exercises too, then it must be a separated task

**Comment by vektor8891** [comment]
@maxinteger The videos are quite long (as long as 1 hr) and they contain several exercises. It would be better if we could reference the exact part of the video. Currently I use [this tool](http://embedyoutube.org/) to embed videos and this allows time stamps too.

**Comment by vektor8891** [comment]
@maxinteger Ok.
