### ISSUE TITLE
Add "auto-hide"/"auto-collapse" option to subtasks

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#446]
Currently, every completed subtasks are displayed for the user. This can be quite inconvenient, especially if the subtasks are referring back to the main description (this is quite common for e.g. geometry exercises where you have several questions for the same figure).

It would be great to have a checkbox for each subtasks where I can choose if the subtask should be hidden or displayed upon completion.

**Comment by maxinteger** [comment]
With the new layout this is not applicable
