### ISSUE TITLE
Link javítása képek beszúrásánál

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#45]
Ha ráviszem az egeret a "Kép beszúrása" gombra, a másik link is aktiválódik:
![image](https://user-images.githubusercontent.com/13850825/29293193-d104c25c-810f-11e7-9bd3-ef2565f2b2ae.png)

**Comment by maxinteger** [comment]
@zsebtanar külön sorba került (később majd ebből lesz valamiféle toolbar)
