### ISSUE TITLE
Solution for text input missing in admin site 

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#468]
it says "object" (e.g. [here](https://zsebtanar.hu/admin/exercise/edit/-M3nd6jjNcR6lj-xFiSs))
![image](https://user-images.githubusercontent.com/38993315/78855829-f81e4000-79f2-11ea-982d-3631e410edad.png)

**Comment by maxinteger** [comment]
not applicable anymore
