### ISSUE TITLE
Címkék javítása

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#47]
Vsz az új bootstrap miatt csúsztak el...

![image](https://user-images.githubusercontent.com/13850825/29369240-021b62fe-8270-11e7-89c9-caa98e0964ba.png)

**Comment by maxinteger** [comment]
@zsebtanar Most néztem meg és nem láttam semmi problémát, próbáld meg úgy frissíteni, hogy a chrome dev-tool is be van kapcsolva, így elvileg ürül a böngésző cache.

Ha a cache ürítés segített akkor zárd le kérlek a feladatot

Hasonló hibák esetén kérlek írd meg a kép mellé, hogy milyen böngészüben annak melyik veziójával történt a probléma

**Comment by zsebtanar** [comment]
@maxinteger igen, most már jó, köszi szépen!
