### ISSUE TITLE
Exercise Catalogue for Grade 5

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#479]
Simple visual summary for grade 5 exercises and videos. Features:

- display all categories
- dropdown menu for each category to display relevant exercises
- ability to rearrange categories & exercises
- add practice link & video to exercises

**Comment by maxinteger** [comment]
@vektor8891 is this the same as #488?

**Comment by vektor8891** [comment]
@maxinteger yes. we can close either one.
