### ISSUE TITLE
Admin site becomes blank in TEST

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#485]
When you write some incorrect pocket-lisp function, sometimes the whole website becomes blank and you lose every unsaved changes. E.g.

-  `(def a ["" + ""])`
- delete `b` from `(def bbb (map (const b) (range y1)))` 
- delete `3` from `(def c[2:3])`
- etc.

**Comment by maxinteger** [comment]
@vektor8891 fixed
