### ISSUE TITLE
Nem használt osztályok elrejtése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#49]
Jelen pillanatban az "1. osztály" is elérhető, noha nincs ide tartozó feladat (volt, de ki lett törölve). Az osztály továbbra is látható, és rá is lehet kattintani a főoldalon:

![image](https://user-images.githubusercontent.com/13850825/29439116-88761834-8389-11e7-8728-1b8087463efd.png)

**Comment by maxinteger** [comment]
@zsebtanar úgy tűnik nincs lekezelve a feladat törlés, amíg nincs kész addig jobb ha nem törölsz több feladatot

**Comment by zsebtanar** [comment]
@maxinteger rendben.
