### ISSUE TITLE
Various bugs in PUBLIC exercise page (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#494]
PROD: https://zsebtanar.hu/exercise/-LcxpzkbOgi7VnKDMQm2
TEST: https://zsebtanar-test.web.app/exercise/-LcxpzkbOgi7VnKDMQm2

Differences/bugs in TEST:
- [x] all the hints show up by default
- [x] "ellenőrzés" button is not working
- [x] "ellenőrzés" button is not aligned to center
- [x] "x" in the top left corner is not working
- [x] grey div moved from bottom to the top of page
- [x] Options do not show up for multiple select questions ([example](https://zsebtanar-test.web.app/exercise/-Lj-EhnHDp6BZh3JtcHc))
- [x] no margin on the top of the page

**Comment by maxinteger** [comment]
all fixed on test
