### ISSUE TITLE
BUG: various bugs in PUBLIC grade summary page (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#495]
PROD: https://zsebtanar.hu/grade/-KpWmzc-r6dB-semHLkc
TEST: https://zsebtanar-test.web.app/list?cls=hu|grade|05

Differences/bugs in TEST:
- [ ] Clicking on tags (e.g. ["érettségi"](https://zsebtanar-test.web.app/list?cls=hu|final-exam) in the first exercise) doesn't work, resulting page show no results (only after manually refreshing the page).
- [ ] If you click on a tag, and then navigate back to the summary page, it also shows no results (only after manually refreshing the page)
- [ ] Clicking on "még" button in the bottom of the page does not do anything

**Comment by maxinteger** [comment]
@vektor8891 

- list pages are working for all users now
- load next ("Még") button works as it is expected, also scroll position does not change

Note: I reduced the number of loaded exercise from 25 to 10

**Comment by vektor8891** [comment]
@maxinteger when you click on a tag, the list still not refreshed automatically. to try: click [here](https://zsebtanar-test.web.app/list?cls=hu%7Cfinal-exam) and then click on the tag "alapműveletek" below the first exercise. the list should be refreshed (e.g. the second exercise do not have this tag), yet nothing changes.

**Comment by maxinteger** [comment]
@vektor8891 
I fixed it, please try again

**Comment by vektor8891** [comment]
@maxinteger it works now, thanks!
