### ISSUE TITLE
BUG: various bugs in PUBLIC main page (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#496]
PROD: https://zsebtanar.hu/
TEST: https://zsebtanar-test.web.app/

Differences/bugs in TEST:
- [x] "Nincs találat" shows up by default in [search page](https://zsebtanar-test.web.app/search)
- [x] Btw why is it that "alk" returns only 4 results but "alka" results 100+ results both in prod and test?
- [x] If you *do not click* on "feladat keresése" on the main page, just start typing something, it doesn't redirect you to the search page, even if you hit enter
- [x] Latest video uploaded to youtube does not show up

**Comment by maxinteger** [comment]
@vektor8891 

- "Nincs találat" only appear when the search term is longer then 2 and the result is empty
- good question, I guess we can change if in Algolia, but this not blocking the release. If you think this is important please create a new issue
- I replaced the fake input with a button in the main navigation
- Latest video is back on the home page

Also I updated the side navigation in mobile view
