### ISSUE TITLE
BUG: various bugs in ADMIN main page (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#497]
prod: https://zsebtanar.hu/admin/exercise
test: https://zsebtanar-test.web.app/admin/exercise

Differences/bugs in TEST:
- [x] exercise status (archived/public/draft etc) is missing
- [x] tags are missing
- [x] when you hover over your mouse on the clone icon it says "wiki oldal másolása" instead of "feladat másolása" which is quite misleading
- [x] button for "megtekintés" (ie. viewing on the public site) is missing
- [x] when you clone an exercise, the prefix "[másolat]" is not added to the title, which makes you think that you are editing the original exercise
- [x] when you save a cloned exercise, the system doesn't append it to the end of the list but puts it to a random place

**Comment by maxinteger** [comment]
@vektor8891 
all fixed, but please note:
- when you clone an exercise the title will not change instead "Másolat" label appears in the control bar
- now exercises are order by creation date, the latest exercise will be the first one

**Comment by vektor8891** [comment]
@maxinteger i get the following error: 
![image](https://user-images.githubusercontent.com/38993315/95904674-d3ba6c00-0d65-11eb-8136-084cff7ebace.png)

**Comment by maxinteger** [comment]
@vektor8891 you are too fast, you tried in the middle of deployment :D
Please try it again

**Comment by vektor8891** [comment]
@maxinteger sorry, my bad :)
i tried again but unfortunately got the same results, even after refreshing with Ctrl+F5

**Comment by vektor8891** [comment]
@maxinteger ok, it works now. it turns out that i wasn't logged in :)

**Comment by vektor8891** [comment]
@maxinteger two minor comments:
- can you pls correct the typo in "Feladat másolása"? (currently it says "Deladat")
- the public view ("megtekintés") is still not available

**Comment by maxinteger** [comment]
@vektor8891 
I can see the "Megtekintés" link:
![image](https://user-images.githubusercontent.com/983050/95921021-6b40ae80-0da8-11eb-9a26-737da401dcdc.png)
Please note the link is not available for unsaved exercises such as new and clone

**Comment by vektor8891** [comment]
@maxinteger I was actually referring to the similar link on the main page (eye icon):
![image](https://user-images.githubusercontent.com/38993315/95935355-0897e480-0da1-11eb-829c-c789e66342d2.png)

But actually it's not crucial, we can let it go for now.
