### ISSUE TITLE
BUG: various bugs in ADMIN exercise page (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#498]
prod: https://zsebtanar.hu/admin/exercise/edit/-L8MUv7TvI1_ILnGRbOa
test: https://zsebtanar-test.web.app/admin/exercise/edit/-L8MUv7TvI1_ILnGRbOa

Differences/bugs in TEST:
- [x] cannot add tags
- [x] cannot change exercise status (archived/draft/public etc.)

**Comment by maxinteger** [comment]
@vektor8891 all fixed
