### ISSUE TITLE
BUG: cannot change hints order in TEST

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#499]
Example: https://zsebtanar-test.web.app/admin/exercise/edit/3hW5sqJBe4U3f7mlU2Ms

The order of hints cannot be changed.

**Comment by maxinteger** [comment]
@vektor8891 Done, please test it

**Comment by vektor8891** [comment]
@maxinteger would it be possible to add the double cross icon similarly to prod? Otherwise it's not clear for new users that this functionality exists at all.
