### ISSUE TITLE
Képek beszúrása

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#5]
- [x] feladatok szövegénél
- [x] útmutatóknál
- [x] drag & drop módszer implementálása (ez nem annyira fontos)
- [x] "ctrl+v" segítségével vágólapon lévő kép beillesztése (~trello) (ez sem)

**Comment by zsebtanar** [comment]
@maxinteger esetleg tudnál ezzel a közeljövőben foglalkozni? csak mert ha ez működne, csomó más feladatot is fel tudnék tölteni...

**Comment by zsebtanar** [comment]
ezek szerint a 3. és a 4. is meg van, ugye? ha az útmutatóknál is meg lehetne csinálni ugyanezt, akkor el lehetne kezdeni föltölteni más típusú feladatokat is. 👍

**Comment by maxinteger** [comment]
@zsebtanar Most már az útmutatóknál is lehet képet beszúrni

**Comment by zsebtanar** [comment]
@maxinteger nagyszerű! 👍

**Comment by zsebtanar** [comment]
@maxinteger tudnád frissíteni a rendszert?
