### ISSUE TITLE
Új feladat beküldése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#50]
- Regisztrálás után lehessen új feladatot beküldeni, amiről a rendszer értesítést küld az info@zsebtanar.hu-ra [Új feladat] tárggyal.
- Az "Új feladat beküldése" gomb a kezdőlapon legyen keresőmező alatt, bejelentkezés nélkül is lehessen látni, de csak bejelentkezés után legyen használható.
- Bejelentkezés után az "Új feladat beküldése" gombra kattintva egy űrlap jelenik meg, ahol a következő adatokat lehet/kell megadni:
  - Osztály (kötelező)
  - Emailcím (csak akkor kell megadni, ha a regisztráció során nem adott meg emailcímet)
  - Témakör (opcionális)
  - Feladat szövege (szövegdoboz, opcionális)
  - Melléklet csatolása (képfeltöltéshez hasonló)
- A feladat csak akkor küldhető be, ha vagy a feladat szövege nem üres, vagy van melléklet.

**Comment by maxinteger** [comment]
@zsebtanar 
Több problémás is van ezzel a feladattal:
 - szerintem a feladat felviteli admin oldal nagyon bonyolult egy átlagfelhasználónak
 - ráadásul sot admin funkcióhoz admin jog kell (osztály/tantárgy/témakör/stb. felvitele) 
 - a részfeladatok megjelenésével tovább bonyolódik a helyzet.
 
A fentiek tükrében valószínűleg a legtöbbször törölni kell a teljes faladatot és nulláról újra felvinni.

Azt javaslom, hogy inkább hozzunk létre egy a "Visszajelzés" popuphoz hasonló felületet ahol beküldik a feladatot és mi beemeljük a rendszerbe.

**Comment by zsebtanar** [comment]
Ok, legyen akkor így.

2017. okt. 4. du. 3:48 ezt írta ("László Vadász" <notifications@github.com
