### ISSUE TITLE
BUG: cannot save new exercise (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#500]
When I try to save a new exercise in TEST, I get the following error:

![image](https://user-images.githubusercontent.com/38993315/94488824-a86f4300-01e3-11eb-961b-d21cdecbae40.png)

**Comment by maxinteger** [comment]
@vektor8891 Which exercise did you try to save?

**Comment by vektor8891** [comment]
@maxinteger it happens only when i create new exercises. (also, i noticed that in these cases the buttons for archiving/deleting etc. don't appear at the bottom). cloning/editing works well.

**Comment by maxinteger** [comment]
YaY 500th issue!

@vektor8891 
I fixed the error and yes when you create a new exercise or clone one then the status options are not available and the it will be saved as draft always.

**Comment by vektor8891** [comment]
@maxinteger thanks, it's working now! way to go! 👍
