### ISSUE TITLE
BUG: cannot update exercise (TEST)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#501]
When I try to modify and save [this exercise](https://zsebtanar-test.web.app/admin/exercise/edit/HVDCeWqHcxZD62Yf52ps) in TEST, I get the following error:
![image](https://user-images.githubusercontent.com/38993315/95942895-59fc9f80-0db2-11eb-9201-5524a0cad947.png)

**Comment by maxinteger** [comment]
@vektor8891 fixed
