### ISSUE TITLE
Cannot add static exercises TEST

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#508]
I tried to create a simple [exercise](https://zsebtanar-test.web.app/admin/exercise/edit/lD6k8LNzCfLTxGzzEZCf) with a 0 solution. Upon saving, I got the following error:

![image](https://user-images.githubusercontent.com/38993315/97068362-c33f9800-1594-11eb-9e5e-d6f9b337d31b.png)

**Comment by maxinteger** [comment]
@vektor8891 Please close it if you can not reproduce it.
