### ISSUE TITLE
Input fields collapse at number list & true/false TEST

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#511]
When you want to add a number list type solution, the design is very confusing:

![Képernyőkép erről: 2020-10-24 01-14-16](https://user-images.githubusercontent.com/38993315/97068561-955b5300-1596-11eb-95ad-5fe392479add.png)

True-false is even more confusing:
![Képernyőkép erről: 2020-10-24 01-17-12](https://user-images.githubusercontent.com/38993315/97068583-cfc4f000-1596-11eb-89f1-f0e91a92166f.png)

**Comment by maxinteger** [comment]
@vektor8891 Could you please check this issue again. I think this is OK now.
