### ISSUE TITLE
BUG: weird behavior of "map" function [POCKETLISP]

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#512]
- **Goal:** generate the following vector: `["AB0","AB1","AB2"]`
- **Solution:**
```
(def concat #(join [%1 %2 %3]))
(def get-item #(concat %1 %2 (str %3)))
(def get-list #(map (get-item %3 %1) (range %2)))
(print (get-list "B" 3 "A")) ; > ["AB0","0A1","102"]
```
- **Issue 1:** Output is different than expected
- **Issue 2:** Applying the `str` function to `concat` instead of `get-item` throws an error:
```
(def concat #(join [%1 %2 (str %3)]))
(def get-item #(concat %1 %2 %3))
(def get-list #(map (get-item %3 %1) (range %2)))
(print (get-list "B" 3 "A")) ; > "Error: Type Error! Expected 'z', but got 're'"
```
- **Issue 3:** Reordering the variables fixes the issue:
```
(def concat #(join [%1 %2 %3]))
(def get-item #(concat %1 %2 (str %3)))
(def get-list #(map (get-item %1 %2) (range %3)))
(print (get-list "A" "B" 3)) ; > ["AB0","AB1","AB2"]
```

**Comment by vektor8891** [comment]
@maxinteger thanks for adding it to the project. i often hit a wall when trying to implement more complex functions. it seems to me there is a bug somewhere which might be related to this issue.

**Comment by maxinteger** [comment]
@vektor8891 It is fixed and deployed on test now
