### ISSUE TITLE
FEATURE: Join-with with line break [POCKETLISP]

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#514]
It would be great it `join-with` would recognize "\n" and the line break would be visible in the text field.

Currently, it just writes "\n" in the text but it doesn't break the line.

```
(def a (join-with "\n" ["a" "b" "c"])) ;  "a\\nb\\nc"
```

**Comment by maxinteger** [comment]
@vektor8891 It is fixed and deployed on test now

Pocket lisp now support 
- `\n` - new line
- `\"` - `"`
- `\\`  - `\`
escape sequences 
so you can join items with new line character
