### ISSUE TITLE
FEATURE: conversion between FractionNumber to Number [POCKETLISP]

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#518]
It would be great to have functions that could convert FractionNumbers to Numbers and vice versa. E.g:

```
(print (num2frac 5)) ; > {"numerator":5,"denominator":1}
(print (frac2num 5/2)) ; > 2.5
```

**Comment by maxinteger** [comment]
@vektor8891 It is fixed and deployed on test now
`number-2-fraction` and `fraction-2-number` added to the stdlib

Note: `number-2-fraction` has 2 parameters
1. accuracy (number of digits)
2. fraction number
