### ISSUE TITLE
FEATURE: more space for scripting [POCKETLISP]

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#519]
It would be great if the size script editor could be adjusted - both vertically and horizontally.

![kép](https://user-images.githubusercontent.com/38993315/98630213-9d322b80-22e8-11eb-910e-9ea6aa415102.png)

**Comment by maxinteger** [comment]
@vektor8891 It is fixed and deployed on test now
With code mirror is not trivial to make is resizable, so I just doubled the height for now.

Please reopen this task if it is not enough.

By the way, in general script should not be longer then 100 lines. If it is more then we have to investigate it and extract the common functions into JS
