### ISSUE TITLE
Hiba beküldése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#52]
- "Hiba jelzése" gomb minden feladatnál szerepel. Bejelentkezés nélkül is látható.
- Meg lehet adni a hibát, ill. egy emailcímet (ha a bejelentkezésnél meg volt adva az emailcím, ez nem szükséges).
- A rendszer a hibát az info@zsebtanar.hu emailcímre küldi [Új hiba] tárggyal, és tartalmazza az észrevétel szövegét, a feladat linkjét, és az illető emailcímét (ha van).

**Comment by maxinteger** [comment]
A korábban megbeszéltek alapján ez beleolvad a #53 feladatba

**Comment by zsebtanar** [comment]
👍
