### ISSUE TITLE
More helpful error messages in code editor

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#521]
It would be great to know e.g. where the error is raised and also to make the error messages more human readable.

![image](https://user-images.githubusercontent.com/38993315/98897165-c1247700-2478-11eb-95e2-4855fa74350b.png)

**Comment by maxinteger** [comment]
@vektor8891 It is fixed and deployed on test now
Code editor now shows errors and the print messages in the next line
also the error messages are fixed and will shows correct type name instead of `re` or `z`
