### ISSUE TITLE
random-int-range with fractions

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#523]
The following command should not return 5. However, it sometimes does:
```
(random-int-range 1 4.8 1)
```

**Comment by maxinteger** [comment]
@vektor8891 `random-int-ranga` is generate range of random integer numbers, if you need a range of random number then you can do this:
`(map (eff (* 4.8 (random))) (range 5))`

if this is a common problem then we can implement a new function.

**Comment by vektor8891** [comment]
@maxinteger I thought `(random-int range a b n)` is supposed to generate a random integer between `a` and `b` with stepsize `n`. It definitely does not return a *range*, only a single number, regardless of the parameters. Can you pls clarify what is the purpose of the third argument?

**Comment by maxinteger** [comment]
`random-int-ranga` removed
