### ISSUE TITLE
Megjegyzés küldése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#53]
- "Megjegyzés" gomb minden feladatnál szerepel. Bejelentkezés nélkül is látható.
- Meg lehet adni a hibát, ill. egy emailcímet (ha a bejelentkezésnél meg volt adva az emailcím, ez nem szükséges).
- A rendszer a hibát az info@zsebtanar.hu emailcímre küldi [Új megjegyzés] tárggyal, és tartalmazza a megjegyzés szövegét, a feladat linkjét, és az illető emailcímét (ha van).

**Comment by maxinteger** [comment]
@zsebtanar 
Arra gondoltam, hogy a megjegyzés és a hibabejelentés funkciókat összevonom egybe "visszajelzés" cím alatt. Ha rákattintasz a gombra akkor ott már kiválaszthatod, hogy gratulálni szeretnél (alapértelmezett) vagy hibát jelenteni. Főleg a felületen szereplő gombok számát szeretném csökkenteni. Egyébként rendszer szinten mindenképpen egy helyen leszne tárolva ezek a visszajelzések.
Mi a véleményed?

**Comment by zsebtanar** [comment]
@maxinteger támogatom az ötletet! (a minél kevesebb gomb ötletét én is előnyösnek tartom UX szempontból)

**Comment by maxinteger** [comment]
@zsebtanar Kész is van, egyenlőre a láblécben helyeztem el egy gombot, később berakom máshova is

**Comment by zsebtanar** [comment]
hibajelzés gomb létrehozása google űrlapokhoz hasonlóan bal alsó sarokban.

**Comment by maxinteger** [comment]
Szerintem ez már nem aktuális, ha még is akkor majd létrehozzunk egy új feladatot
