### ISSUE TITLE
Bug: cannot save exercise in test

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#543]
When I want to save a valid exercise on the test server, I get the following error in the console:

```
firebase.ts:32 POST http://localhost:5001/zsebtanar-test/us-central1/api/api/exercise/ 500 (Internal Server Error)
```

**Comment by vektor8891** [comment]
@maxinteger I still experience this on localhost even after updating my develop branch.

**Comment by vektor8891** [comment]
Saving existing exercises doesn't work either.

**Comment by maxinteger** [comment]
Accidentally I deployed the app with the production configuration to the test server.
All good now.
