### ISSUE TITLE
Bug: cannot log in to test server with Google Oauth

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#544]
When I try to log in to the [test server](https://zsebtanar-test.web.app/login) using Google Oauth, I get the following error:

```
This domain (zsebtanar-test.web.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab.
```

**Comment by maxinteger** [comment]
Accidentally I deployed the app with the production configuration to the test server.
All good now.
