### ISSUE TITLE
Display PLNumber correctly

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#550]
Display PLNumber as decimal string, not as JS object.
Actual:
```
(print 10.345) ;> {"intValue":10345,"decimals":3}
```
Expected:
```
(print 10.345) ;> "10.345"
```

**Comment by maxinteger** [comment]
@vektor8891 already fixed, see here: https://maxinteger.github.io/pocket-lisp-page/sandbox.html
