### ISSUE TITLE
Factors with decimals

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#551]
Enable defining factors using decimal numbers e.g. `12.3/12.4`

**Comment by maxinteger** [comment]
@vektor8891 what is the use case for this feature?

**Comment by vektor8891** [comment]
@maxinteger It would be useful for cases when e.g. users have to extend a given fraction to integers.

**Comment by maxinteger** [comment]
Are they except format like `12.3/12.4` in real life exams?

**Comment by vektor8891** [comment]
Agreed. Let's close this for now. If we encounter real-life examples, we can open this again.
