### ISSUE TITLE
PLHashmap is not displayed correctly

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#555]
When I run the `(print {:key "value"})` script in the [sandbox](https://maxinteger.github.io/pocket-lisp-page/sandbox.html) I get the correct results (`{key -> value}`). However, when I run the same on the [test server](https://zsebtanar-test.web.app), I only get `{}`.

**Comment by maxinteger** [comment]
@vektor8891 done
