### ISSUE TITLE
Dynamic exercise not working

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#557]
[This](https://zsebtanar-test.web.app/exercise/6DyMXWXEhB68PjLuktyW) exercise gives an error:

```
{
   "status": "error",
   "statusCode": 500,
   "message": "Exercise request error",
   "details": {}
}
```

**Comment by maxinteger** [comment]
@vektor8891 What do you mean "not working"?
- Can not save it?
- Can not load it?
- Can not check the user answers?
- which endpoint returns with this error?

**Comment by maxinteger** [comment]
@vektor8891 fixed
it was a deploy issue
