### ISSUE TITLE
"Rólunk" oldal tartalma

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#56]
Jó lenne már most felvenni egy oldalt ami tartalmazza, hogy
- mi az a Zsebtanár alapítvány
- kik állnak mögötte
- mik a céljaink
- hogyan tudsz segíteni 
- stb.

Ennek a szövegezését szeretném rád bízni @zsebtanar 
Nem olyan sürgős, de jó lenne ha már induláskor ott lenne egy rövid bemutatkozás

**Comment by zsebtanar** [comment]
@maxinteger jogos felvetés. igyekszem Áronnal összeállítani egy Magunkról doksit.
