### ISSUE TITLE
Dynamic exercise check not working

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#562]
1. Open [this](https://zsebtanar-test.web.app/exercise/pKUN4d15GB3f8BqxSgA6) exercise
2. Write down the answer shown.
3. Check your answer.

Instead of moving on to the next subtask, your answer is rejected (despite being good).

**Comment by maxinteger** [comment]
@vektor8891 fixed

We used the shuffle function from the PocketLisp std lib which use the JS random generator instead of our PseudoRandomNumberGenerator
