### ISSUE TITLE
Dynamic exercise fails to update after modifying script

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#563]
1. Open [this](https://zsebtanar-test.web.app/admin/exercise/edit/pKUN4d15GB3f8BqxSgA6) exercise
2. Modify the description of the first subtask (currently its content is: "Megoldás: @letter@")
3. Save the exercise (but don't refresh the page!)
4. Click in the script editor and hit Enter
5. Save the exercise again
6. Refresh the page

Result: The update you added in 2) is lost.
Note: If you refresh the page after 3), the modification won't disappear.
Note 2: If you edit the main description in 2), the bug doesn't appear.

**Comment by maxinteger** [comment]
@vektor8891 Nice one :D

**Comment by maxinteger** [comment]
@vektor8891 Fixed
