### ISSUE TITLE
Cannot open exercise

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#565]
Opening [this](https://zsebtanar-test.web.app/exercise/-Lx9_ippYFGx7Ki6Jjcw) exercise gives this error:
```
{
   "status": "error",
   "statusCode": 500,
   "message": "Exercise request error",
   "details": {}
}
```

**Comment by maxinteger** [comment]
@vektor8891 I fixed.
The base issue is the linked exercise is not exist. Usually the exercise id does not contains `_`.

Now the exercise will redirect to the `/page-not-found` page

**Comment by maxinteger** [comment]
@vektor8891 I fixed.
The base issue is the linked exercise is not exist. Usually the exercise id does not contains `_`.

Now the exercise will redirect to the `/page-not-found` page
