### ISSUE TITLE
How to generate random fractions?

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#568]
Should I use this command to generate a random fraction?
```
(def nom (random-int 1 19))
(def denum (random-int 1 19))
(def fraction nom/denum)
```

**Comment by vektor8891** [comment]
@maxinteger Nevermind, I've found the solution (`number-2-fraction`).

**Comment by maxinteger** [comment]
@vektor8891 `number-2-fraction` is one solution, but you can use the factory function as well: `(FractionNumber 1 2)`
unfortunately it does not work so this is still a valid issue

**Comment by maxinteger** [comment]
@vektor8891 
In PL stdlib 0.11.0 it works now
and it works for other types as well

Not all of them interesting but the `FractionNumber` and `HashMap` very useful for programmatically create them 

```
(def bool (Bool true))
(def string (String "Hello"))
(def num (Int 42))
(def num2 (Float 42))
(def fraction (FractionNumber nom denum))
(def hmap (HashMap ["a" "b" "c"] [1 2 3]))
(def vec (Vector 1 2 3))
```

I will deploy it soon
