### ISSUE TITLE
Cannot create random num-list

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#569]
1. Open [this](https://zsebtanar-test.web.app/admin/exercise/edit/pKUN4d15GB3f8BqxSgA6) exercise
2. Add new num-list (számlista) field 
3. Name it `list`
4. check dynamic
5. Click OK

It doesn't allow you to save the exercise because you didn't specify the accuracy. However, if you write any number in the field, and try to save it afterwards, the website goes blank.

**Comment by maxinteger** [comment]
@vektor8891 fixed.
