### ISSUE TITLE
Uncaught Error: Seed must be a positive integer number

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#570]
1. Open [this](https://zsebtanar-test.web.app/exercise/EbdRL0kl6bRnVn1ziQG4) exercise
2. Keep refreshing the page
3. At some point the site crashes with the following error message: `Uncaught Error: Seed must be a positive integer number`

**Comment by maxinteger** [comment]
@vektor8891 fixed
