### ISSUE TITLE
Shuffle doesn't work properly

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#572]
1. Open [this](https://zsebtanar-test.web.app/exercise/EbdRL0kl6bRnVn1ziQG4) exercise
2. Keep refreshing the page

As you can see, `a` and `c` almost never appears among the list, while `b` and `d` appear much more often.

**Comment by vektor8891** [comment]
@maxinteger I had a look at this. It seems that `shuffle` works correctly. Even on the admin site, the letters are shuffled well. However, this is not the case on the public site. Is there a way to see which seed is used for a given exercise? I guess that may be causing the problem.

**Comment by maxinteger** [comment]
You can see the seed when you send the user answer to the server for validation:
![image](https://user-images.githubusercontent.com/983050/113929934-8dac0580-97e8-11eb-9207-8f967db31485.png)

But you can modify the seed value if you put the `?s=<seed-value>` query parameter into the URL
for example:
> https://zsebtanar-test.web.app/exercise/EbdRL0kl6bRnVn1ziQG4?s=42

**Comment by maxinteger** [comment]
@vektor8891 fixed

**Comment by vektor8891** [comment]
@maxinteger Thanks for the info, it's very helpful.
