### ISSUE TITLE
Number input field too small

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#576]
1. open [this](https://zsebtanar-test.web.app/exercise/-LfSE6aOE8hwa3n6TjoK) exercise
2. As you can see, the input field is so small that you cannot see the number you want to write into it

**Comment by maxinteger** [comment]
@vektor8891 fixed

**Comment by vektor8891** [comment]
@maxinteger I still see the issue.

**Comment by vektor8891** [comment]
@maxinteger Issue resolved after clearing the cache. Thanks for the suggestion.

**Comment by vektor8891** [comment]
@maxinteger Do you know how I can see this in Firefox as well? I tried to clear the cache but I still don't see the impact (obviously the error is on my side because it works with Chrome).
