### ISSUE TITLE
Hints do not appear

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#577]
1. For [this](https://zsebtanar-test.web.app/exercise/-LetI61Plg2Wids96JTu) exercise, the hints button doesn't appear even if the solution is wrong.
2. For [this](https://zsebtanar-test.web.app/exercise/-M3intdKVCz_be3KTWre) exercise, the button does appear but doesn't work.

**Comment by maxinteger** [comment]
@vektor8891 fixed

**Comment by vektor8891** [comment]
@maxinteger I still see the issue.

**Comment by vektor8891** [comment]
@maxinteger I do see some hints in the first exercise on the [admin site](https://zsebtanar-test.web.app/admin/exercise/edit/-LetI61Plg2Wids96JTu).

I confirm that the second issue is resolved.

**Comment by maxinteger** [comment]
@vektor8891 you are right, https://zsebtanar-test.web.app/exercise/-LetI61Plg2Wids96JTu has hints but only for the second and third sub tasks:
![image](https://user-images.githubusercontent.com/983050/113019564-a9c0fe80-9179-11eb-88e7-563725edac9e.png)

**Comment by vektor8891** [comment]
@maxinteger Good point, sorry I've missed that. I tried to check the second/third subtask but it doesn't accept the correct answer for the first question:
![kép](https://user-images.githubusercontent.com/38993315/113030598-c77f6b00-915b-11eb-9258-9fd14028379b.png)

I get the following error:
```
Access to fetch at 'https://zsebtanar-test.firebaseapp.com/api/exercise/-LetI61Plg2Wids96JTu/check' from origin 'https://zsebtanar-test.web.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by maxinteger** [comment]
@vektor8891 I think you get this error because you not logged in. If you log in and then the hint works then you can close this issue because it is the same as #566

**Comment by vektor8891** [comment]
@maxinteger Issue is resolved after logging in. I think we can close it too.
