### ISSUE TITLE
Do not highlight next subtask before user clicks next

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#578]
1. Open [this](https://zsebtanar-test.web.app/exercise/pKUN4d15GB3f8BqxSgA6) exercise
2. Write in the right solution
3. Click the check button

In the progress bar on the top, the next subtask is already highlighted even before the user clicks "next". This is very confusing from UX experience. I suggest highlighting the next subtask only after the user clicks "next".

**Comment by maxinteger** [comment]
@vektor8891 you are right, this is clearly a bug here.
I change a bit, so you will see now the fallowing colors
- gray - not started
- blue - selected
- green - finished
- yellow - current

Maybe we have too many colors here, but we can review it when we do the re-design

**Comment by vektor8891** [comment]
@maxinteger A couple of more comments from user experience:
- Do not highlight the next subtask (currently with yellow) until the user clicks "next". Because even by highlighting with a different color, it gives an impression that we have already decided for the user. This means we can drop yellow altogether, we can just keep the bar gray.
- Do not change the color of the finished subtask (currently marked with green). It confuses the user (feels like my achievement is lost somehow). This means we can drop green altogether - let's just use blue instead.
- Using only 2 colors (solved/not yet solved) would make it easier to interpret the progress bar:
![kép](https://user-images.githubusercontent.com/38993315/114257595-0056e580-998f-11eb-869f-e95e67ebdafe.png)
- Also, currently, the last bar is not changed even after solving all subtasks which leaves the user with a sense of not having finished yet:
![kép](https://user-images.githubusercontent.com/38993315/114257663-82470e80-998f-11eb-8c4f-70b2278cdf80.png)


These are my suggestions

**Comment by maxinteger** [comment]
@vektor8891 Updated

**Comment by vektor8891** [comment]
@maxinteger Thanks for reducing the number of colors. For the sake of simplicity, I suggest using only two colors (light green for solved and light gray for not solved subtasks) because shaded versions can be very close, which make it hard to understand where the user is now:

![kép](https://user-images.githubusercontent.com/38993315/114973132-d64d6980-9e4d-11eb-8e4a-37d326afa7e7.png)

Also, the last bar is still not completely the same color even after solving the exercise:

![kép](https://user-images.githubusercontent.com/38993315/114973394-64295480-9e4e-11eb-87b0-561118cb5081.png)

**Comment by maxinteger** [comment]
@vektor8891 the darker version shows which one is the selected task.
It is necessary since you can select any solved tasks.

The second point is valid, should not show the darker green after all sub task finished
