### ISSUE TITLE
Correct exercise not accepted for num list

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#579]
1. Open [this](https://zsebtanar-test.web.app/admin/exercise/edit/Eo5oVErNPY9blhTRRPta) exercise
2. Write in the correct answer

The correct answer is not accepted.

**Comment by maxinteger** [comment]
@vektor8891 fixed

**Comment by vektor8891** [comment]
@maxinteger Thanks a lot for fixing it. I see that an extra "value" string appears in front of the input boxes. Would it be possible to remove them?

![kép](https://user-images.githubusercontent.com/38993315/113065017-1f32cc00-9186-11eb-9f92-f7d48f8e8eca.png)

**Comment by maxinteger** [comment]
@vektor8891 Fixed
