### ISSUE TITLE
Delete user input when moving on to next subtask

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#580]
1. Open [this](https://zsebtanar-test.web.app/exercise/-LetI61Plg2Wids96JTu) exercise
2. Write in the correct solution (24)
3. Click submit

Your solution (24) remains in the input field even after you move on to the next subtask.

**Comment by maxinteger** [comment]
@vektor8891 Fixed

**Comment by vektor8891** [comment]
@maxinteger I have cleared the cache and now the website doesn't accept the correct answer (24).

**Comment by maxinteger** [comment]
@vektor8891 fixed
