### ISSUE TITLE
BinaryChoice radio button issues

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#590]
- [ ] radio buttons are misplaced
- [ ] default true/false labels are not displayed

Example: https://zsebtanar-test.web.app/exercise/JrtTog3RVITzNuJ7lpvt

![kép](https://user-images.githubusercontent.com/38993315/114257894-ee764200-9990-11eb-8575-89cf2fdad44e.png)

**Comment by maxinteger** [comment]
@vektor8891 fixed
