### ISSUE TITLE
Cannot update exercise (test)

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#594]
1. Open this exercise: https://zsebtanar-test.web.app/admin/exercise/edit/-M3ilWghjke9wE-bD4oT
2. Remove the video from the first hint.
3. Save the exercise
4. Refresh the page

The exercise has not been refreshed.

**Comment by maxinteger** [comment]
@vektor8891 Fixed. It was a bug in the BE validation process.
