### ISSUE TITLE
Generate difficulty level for exercises

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#628]
At the top of the exercises, 1, 2 or 3 nuts appear which show the difficulty of the task:

![image](https://user-images.githubusercontent.com/38993315/131155406-0245e7a8-cb05-402b-ae06-cd0be1c8eed9.png)

Currently, this is generated manually:

```
; DIFFICULTY ICONS
(def level (random-int 1 3))
(def level-icon "@[walnut_small.png](https://firebasestorage.googleapis.com/v0/b/zsebtanar-prod.appspot.com/o/storage%2Fexercise%2F5jCUMj1TVmKOUBWKVrt5?alt=media&token=5fdf0f50-2f06-485a-b553-825a2aceaf84 =40x)")
(def level-icons (join (map (const level-icon) (range 1 level))))
```

The goal is to:

- [ ] generate a random number between 1, 2 and 3
- [ ] make it accessible in the editor under the name `level`
- [ ] generate `level` number of nuts at the top of the exercises

**Comment by maxinteger** [comment]
done
