### ISSUE TITLE
Feladat szerkesztő UX

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#63]
Jelen formájában szinte használhatatlan.

**Comment by zsebtanar** [comment]
@maxinteger szted ebben esetleg kérhetjük Gergő segítségét?

**Comment by maxinteger** [comment]
@zsebtanar 
Megkérdezhetjük. 
Eredetileg úgy terveztem, hogy a prototípus jelleg miatt elkezdtek kísérletezni egy másik elrendezéssel.

**Comment by zsebtanar** [comment]
@maxinteger jó ötlet, akkor lehet, h érdemes várni, míg két verzió van, mert azt könnyebb összehasonlítani (akár tanárokkal is).
