### ISSUE TITLE
Simple text exercise not working

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#638]
Example in [prod](https://zsebtanar.hu/exercise/0h1u2Hg61WGmJpf1CU1l) and [test](https://zsebtanar-test.web.app/exercise/nFaZUXkigJ8q8DbMa8I1).

**Comment by maxinteger** [comment]
@vektor8891 Sorry but this is an issue in the PL script.
The solution function returns with a single string instead of an array of strings (or array of one string)

```
(def n "text")
(def solution-n (const n))
```

it should be
```
(defn solution-n [] ["text"])
```

**Comment by vektor8891** [comment]
@maxinteger I found the issue: the code works if the string is low caps but it won't work for large caps. E.g. if you try this it won't work:

```(defn solution-n [] ["TEXT"])```

**Comment by maxinteger** [comment]
@vektor8891 this is completely different problem, but we can keep it in this thicket

By default we check the text in case in-sensitive mode, but only the user input transformed to lower-case. but we should do the same for the solution just in case :)

I will take a look

**Comment by maxinteger** [comment]
@vektor8891 I fixed the issue, but I changed back-end code, so you can not see the change until I deploy it on the test env

**Comment by vektor8891** [comment]
@maxinteger No problem - thanks for the fix!
