### ISSUE TITLE
Cannot access admin page on mobile

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#639]
- After you log in as an admin, click on the right menu and select "Admin".
- The menu icon moves to the upper **left** side.
- When you want to click on it, the screen goes blank:

![IMG_0279](https://user-images.githubusercontent.com/38993315/132435066-0f2aaf81-ee7b-4cbb-8a24-2cf5a344e981.PNG)

**Comment by maxinteger** [comment]
@vektor8891 I will fix this issue, but the admin page is not optimised for mobile especially the exercise editor

**Comment by vektor8891** [comment]
@maxinteger Understood. I'll keep this in mind in the future.
