### ISSUE TITLE
Igaz-hamis mező egyszerűbben

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#64]
Javaslom, hogy az igaz hamis mező "igaz" ill. "hamis" válaszopcióit ne lehessen átírni (arra ott van a feleletválasztós). A redmentás felület így néz ki:
![image](https://user-images.githubusercontent.com/13850825/29745801-531e8d40-8ac5-11e7-8066-0d727f69c08e.png)

Egyébként egy bug-ot is észrevettem: az "igaz"-t át tudtam írni, de a "hamis"-t valamiért nem:
![image](https://user-images.githubusercontent.com/13850825/29745806-729f0ece-8ac5-11e7-9cdc-d5a0d36f5226.png)

**Comment by maxinteger** [comment]
@zsebtanar Ezt nem teljesen értem. Az hogy müdosíthatsz az igaz/hamis szüvegen teljesen opcionális, alapértelmezetten az Igaz/Hamis szöveg fog mejlenni. Ráadásul a képbeszúrás miatt akár alma és körte is lehet az igaz/hamis helyett ami pl asós feladatoknál nem egy rossz dolog....
Ha csak az átírhatóság az egyetlen különbség Igaz-hamis és a feleletválasztó mező között akkor semmi szükség az igaz-hamis mezőre, de a korábbi megbeszélés alapján ez nincs így és több esetben sem váltható ki.

Kicsit úgy érzem, hogy csak azért kellene kivenni ezt a funkciót, hogy jobban hasonlítson a redmentara.

**Comment by zsebtanar** [comment]
@maxinteger elsősorban az egyszerűség miatt lenne célszerű fixálni az igaz/hamis szövegeket. ugyanis ami a redmentában 1 sor, az most nálunk 4 (sőt, a kérdéssel együtt 5). sztem ha valaki az "igaz/hamis" típusú kérdésre kattint, akkor vsz. nem akarja átírni az igaz/hamist - akkor inkább feleletválasztós kérdést választ, ami ugyanazt tudja.

**Comment by maxinteger** [comment]
@zsebtanar :)
Ha jól emlékszem akkor pont én mondtam a feleletválasztónál, hogy felesleges az igaz-hamis, de hála neked beláttam, hogy a kettő merőben más mind megjelenésben mind funkcióban, épp ezért nem értem az előző megjegyzésed. Az sem teljesen világos, hogy miért baj, hogy 5 sor beviteli mező van, korábban a feleletválasztónál is egy sor volt minden de túlzsúfoltnak éreztem és rontotta az átláthatóságot is a sok gomb ezért felbontottam az változtatható értékeket külön sorokba. Ráadásul alapértelmezetten az igaz/hamis van beállítva így a tanárnak csak a megoldást kell beállítania.
A szövegmódosítás bővíti a komponens felhasználhatóságát és pl elsősöknek beszúrhatunk almát/körtét igaz/hamis helyett.

Négy opciót látok:
- így hagyjuk
- a tanárokra bízzuk
- elrejtjük egy gomb mögé és csak akkor látszik ha rányomsz a gombra és/vagy már korábban módosítottad
- töröljük a funkciót

**Comment by zsebtanar** [comment]
@maxinteger sztem semmiképpen se törüljük, mert ez egy tök jó funkció, még akkor is, ha ketten másképp látjuk :D azt javaslom, hogy egyelőre hagyjuk így akkor, és majd később esetleg a tanárok eldönthetik, hogy nekik melyik tetszik jobban. ehhez mit szólsz? :)

**Comment by maxinteger** [comment]
Akkor ezt most lezárom :)
