### ISSUE TITLE
Mezők törlése új feladatszerkesztő nézet

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#67]
Ha a "útmutató" után az "megoldás"-ra kattintasz, utána nem tűnik el a szöveg:

![image](https://user-images.githubusercontent.com/13850825/29920756-42db5f98-8e4f-11e7-94cd-33706b92f2b3.png)

**Comment by maxinteger** [comment]
@zsebtanar Köszi a hiba bejelentést.
- törölted a böngésző cache-t mielőtt kipróbáltad az új felületet?
- pontosan melyik feladatnál jön ki a probléma (amiket megnétem ott nem volt semmi)
- legközelebb nyugodtan felveheted a hibát az eredeti feladathoz  (#63) mert még nincs lezérva és még messze nincs kész.

**Comment by zsebtanar** [comment]
@maxinteger 

- igen
- az új feladat hozzáadásánál
- rendben, köszi! :)

**Comment by maxinteger** [comment]
@zsebtanar 
sikeresen megjavúlt
