### ISSUE TITLE
Képernyőrögzítő telepítése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#68]
- smartlook, hotjar stb.
- UX fejlesztésnél hasznos lehet

**Comment by maxinteger** [comment]
@zsebtanar 
A hotjar jónak tűnik illetve itt egy másik is https://mouseflow.com/. Lehet, hogy próbaképpen mindkettőt feltelepítem :)

Viszont nagyon fontos lenne, hogy ezekről írjuk egy adatvédelmi tájékoztatást a jogi problémák elkerülése végett.

**Comment by zsebtanar** [comment]
ha nem akadnak össze, akkor sztem mehet. a jogi disclaimert [itt](https://www.goyaphone.eu/cookies) pl. a cookie infó szövegbe tették. de biztos vannak más példák is.

**Comment by maxinteger** [comment]
@zsebtanar ha jól értem akkor te már telepítettél egy ilyen csomagot. Lezárhatjuk ezt a feladatot?
