### ISSUE TITLE
Szövegszerkesztő

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#69]
Alapvetően a github-on is használt szerkesztőre lenne szükségünk

- [x] **Mintaszöveg beillesztése** (ha nincs kijelölve szöveg): Ha egy felhasználó nem ismeri a markdown-t, és csak rákattint a B-re, azt hiszi, hogy - mint a wordben - itt is innentől kezdve félkövéren fog tudni írni. Szóval ilyenkor érdemes beírni valami teszt szöveget is, hogy lássa, hogy hogy működik a dolog (félkövérnél, dőltnél is). Listáknál ugyanezt meg lehet csinálni (pl. egy 3 elemű minta listát beilleszteni)
- [x] **Áthúzott kihagyása**: nagyon ritkán lesz rá szükség
- [x] **Matematikai szimbólumok**: először is sztem a dollár helyett jobb, ha szöveggel kiírjuk (pl. "Egyenlet beszúrása"). Kattintásra automatikusan kitesz egy egyenletet $-jelekkel (pl $$E=mc^2$$). -
- [x] **Súgó képlethez**: Jó lenne a leggyakrabban használt kifejezéseket (gyök, hatvány, koszinusz, logaritmus stb.) is bevinni a súgóba... lásd #20

**Comment by maxinteger** [comment]
Kész
