### ISSUE TITLE
Feladat állapot tárolása és kezelése

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#7]
A (privát) feladat DB model tartalmaz egy `state` paramétert. Lehetésges állapotok:

- `draft` - Ha valaki beküld egy feladatot akkor előbb `draft` állapotba kerül, ha az admin ellenőrizte és elfogadta akkor kerülhet át `active` státuszba. Törtlés esetén (a `trash` állapot kihagyásával) egyből töröljük.
- `active` - A feladat elfogadása után kerül ebbe az állapotba, ekkor készül el a publikus változata a feladatnak + ekkor válik kereshetővé. Törlés esetén `trash`
- `trash` - ebben az állapotban a feladat nem kereshető és nem érhető el a publikus oldalon, de az admin felületen még visszaállítható

Lehetséges állapot átmenetek:
- `draft` -> `active`
- `draft` -> végleges törlés
- `active` -> `trash`
- `trash` -> `active`

**Comment by maxinteger** [comment]
Annyit módosítottam, hogy csak `draft` esetén lehet véglegesen törölni és nem lehet `active`-ból `draft`-ba vissza lépni, ezzel is megelőzve a végleges törlést olyan feladatok esetén amelyeket már megoldottak.

Aktív feladat szerkesztésének/ellenőrzésének problémája egy másik feladat lesz
