### ISSUE TITLE
Multi choice exercise not working

### ISSUE THREAD

**Issue by vektor8891** [zsebtanar/zsebtanar-proto#701]
1. open this exercise: https://zsebtanar.hu/exercise/skqHTVTvDsdjB2PfdYPI
2. this is the error i get:
![image](https://user-images.githubusercontent.com/38993315/147602242-aec4bf94-ed96-4be1-8589-e5cd1d47caaa.png)

**Comment by maxinteger** [comment]
@vektor8891 Fixed
If you have other exercises with the same issue than you might have to go to the admin and save the exercise again.

**Comment by vektor8891** [comment]
@maxinteger Thanks a lot for the fix!
