### ISSUE TITLE
Részfeladatok extrák

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#73]
Így gondoltam (ha valami nem világos, szólj nyugodtan):

![image](https://user-images.githubusercontent.com/13850825/30241223-755d9a44-957f-11e7-8b3c-c2310f3da0e3.png)

**Comment by maxinteger** [comment]
@zsebtanar Szuper! de azért van pár kérdésem, mert továbbra is úgy látom, bár a diák szempontjából hasznos lehet, de a tanár/admin oldalon jelentősen bonyolódik a helyzet
- csak egy feladat elírás van, vagy egy "fő" leírás és opcionálisan részfeladatonként is?
- útmutatók
    - a útmutatók is részfeladatonként kell definiálni különben a diáknak meg kell nézni az összeset ha az utolsó részfeladatnál akad el
    - a diák megnézheti a már megoldott részfeladat útmutatókat is?
- több megoldás mező is megadható egy részfeladathoz?
- lehet definiálni a részfeladat nehézségét?
- már a rajzodon is látszik, hogy ismét egy oldalra kerül a megoldás mező és az útmutató lista szóval erre is ki kell találni valami okosat, de ugye a részfeladatok behoznak egy újabb navigációs szintet, szóval nem lesz egyszerű :)

**Comment by zsebtanar** [comment]
@maxinteger jók a kérdések :). íme a válaszok:

- csak egy feladat elírás van, vagy egy "fő" leírás és opcionálisan részfeladatonként is? **van egy fő feladatleírás, és minden részfeladathoz van opcionálisan további szövegmező is**
- útmutatók
    - a útmutatók is részfeladatonként kell definiálni különben a diáknak meg kell nézni az összeset ha az utolsó részfeladatnál akad el **igen**
    - a diák megnézheti a már megoldott részfeladat útmutatókat is? **igen, a felhasználó szabadon lépegethet a már megoldott részfeladatot között, és az útmutatókat is megnézheti, ha van**
- több megoldás mező is megadható egy részfeladathoz? **nem, mindig csak 1 kérdés van egy részfeladatnál**
- lehet definiálni a részfeladat nehézségét? **sztem nem fontos, de ha gondolod, akkor lehet implementálni**
- már a rajzodon is látszik, hogy ismét egy oldalra kerül a megoldás mező és az útmutató lista szóval erre is ki kell találni valami okosat, de ugye a részfeladatok behoznak egy újabb navigációs szintet, szóval nem lesz egyszerű :) **igen, valóban - majd meglátjuk, hogy mennyire lesz bonyolult :)**

**Comment by zsebtanar** [comment]
ami még fontos, hogy **minden részfeladathoz tartozik egy útmutató**, ahol az addigi részfeladatok eredménye van összefoglalva. ez minden részfeladattal egyre bővül, de fontos, hogy minden részfeladat útmutatóját külön lehessen szerkeszteni (ugyanis van, hogy "tömöríteni" kell az útmutatókat, nem elég bemásolni egymás alá az összes addigit).

ami szintén fontos, hogy hasznos lenne, ha lehetne **"alternatív" részfeladatot** meghatározni (azaz, ha elrontja, akkor nem ugyanazt kapja, hanem egy másikat). így először lehetne nehezebb részfeladatot megadni (ahol pl. neki kell beírni a megoldást), és ha elrontja, akkor lehet könnyíteni (pl. 4 lehetőségből kell kiválasztania a helyeset).

egyelőre a részfeladatoknál a következő típusokra volt szükség:
- egyszerű szám mező
- egyszeres választás
- többszörös választás (-> itt megint vigyázni kell, hogy "diákbiztos" legyen, azaz, kevés próbálgatással rá lehessen jönni a megoldásra - pl. úgy, hogy minden kiválasztott opcióról külön kap visszajelzést a felhasználó).

itt van néhány példa.

**Comment by maxinteger** [comment]
@zsebtanar 

- Minden részfeladathoz külön ötmutatóval egyetértek, bár ne felejtsük el, hogy a képernyőn több lehetőségünk van a papír formátummal szemben. Pl megjelenithejük az előző részfeladat eredményeit, de akár az össze szöveget is kisebb betűmérettel, vagy elrejthető/megjeleníthető formában, és egy lehet, hogy kevésbé fontos a feladat újrafogalmazása.

- Az  "alternatív" részfeladatokkal több problémám is van:
  1. Miért gondoljuk, hogy a beviteli mező okozza a problémát és nem pl a feladat leírás (azaz a feladat megértése) vagy más tudás beli hiányosság. Ha belegondolunk akkor a következő történik. Beírom a megoldásomat, de nem jó ezért kapok egy felelet választót, egyrészt ez nem életszerű mert sem az érettségin sem az életben nincs ilyen opció :) másrészről rászoktatjuk a diákot, hogy tippeljen ugyanis ha minden feladatnak van alternatív megoldása akkor igazából nyugodtan elronthatom az elsőt és majd az alternatívát betippelem, szóval egyáltalán nem kell gondolkodni a nehezebb részen (max külső motivációval lehet ezen javítani)
  1. Ezzel azokat is "rákényszerítjük" a felelet választásra akik amúgy kitudnák számolni a megoldást, de mondjuk csak elgépelték
  1. Saját magunkat is korlátozzuk ha olyan beviteli mezőkben gondolkodunk amikből könnyen felelet választó alakítható
  1. extra komplexitás az admin oldalon, főleg UX szempontjából
Szerintem inkább az elrontott feladat esetén a diák  választhat a következőkből: 
  - "Megpróbálom újra", 
  - "Kérek segítséget", 
  - "Következő részfeladat"
Így kap lehetőséget a feladat újra megoldására illetve kérhet segítséget a leíráshoz ami rávezetheti a diákot a helyes megoldásra, illetve át is ugorhatja (utóbbi problémás lehet ha a következő részfeladat épít az előzőre, de ha ez így van akkor akár a következő feladatra is ugorhatunk...)
A felelet választós feladatokkal nincs bajom, de így egyszerűsítünk le egy feladatot akkor az olyan mint mikor szánalomból akarnánk valaki átrugdosni az által hogy tálcán kínáljuk a megoldást ahelyzett, hogy megértené és legközelebb már tudná miről van szó.
  
Végül egy ötlet. a feladat megoldása után esetleg be lehetne rakni egy rövid magyarázatot, hogy miért az a helyes megoldás. Itt akár be is linkelhetünk matekkal foglalkozó oldalakat

Lehet a többieket is érdemes lenne bevonni ebbe.

**Comment by hortom** [comment]
Az alternativ reszfeladatokrol: abszolut egyetertek a fentiekkel, hogy ne akarjunk masik, plane konnyebb megoldasi utat mutatni. Nem eletszeru, mert sem dolgozatban sem erettsegin nem fordulhat elo hasonlo. Plusz azert vegyuk figyelembe, hogy milyen koru gyerekekrol van szo. Az erettsegire keszulnek, nem a negy alapmuvelet gyakorlasara. Nem tudom mennyire egyszeru altalanossagban egy reszfeladat de gyanitom, hogy "elegge". Azaz egy jo kepessegu felsotagozatos is boldogulna vele tobbsegeben. Na innen mar nem latom ertelmet lebutitatni a feladatokat meg egyszerubbre.
Azt akarjuk gyakoroltatni, amivel valoban szembe fog nezni a diak. (Ne jarjunk ugy, mint az egyszeri egyetemi oktato, aki olyan konnyu feladatokat visz gyakorlatra, amit mindenki meg tud oldani, csak elfelejti, hogy ezek es a valos feladatok kozott van meg 10 lepes, igy mndenki egyest ir ZH-n es nem erti, miert.)

**Comment by zsebtanar** [comment]
Sziasztok!
Köszi az észrevételeket. Nyitott vagyok a javaslatokra. Én sem támogatom, hogy a honlap ne segítse a diákok gondolkodását, viszont az szeretném, hogy *aki szeretné*, végig tudjon menni a feladatokon. A nem teszt alapú megoldásokkal az a baj, hogy van annak esélye, hogy elakadsz - ilyet tapasztaltam már tesztelés közben. Ez pedig baromira megakasztja a flow-t...

Én inkább túl egyszerűre állítanám a nehézséget, mint túl nehézre, és inkább folyamatosan nehezíteném. Pl úgy, hogy másodszor már csak akkor kap érte pontot, ha nem veszi igénybe a könnyített részfeladatokat.

Tudom, hogy nem életszerű, viszont így fenn tudjuk tartani a flow-élményt.

Mi a véleményetek erről?

**Comment by maxinteger** [comment]
@zsebtanar Egyetértek abban, hogy valahogy segítenünk kell a diákokat a nehézségeken való túljutásban, de szerintem jobb lenne ha nem a megoldási halmazt csökkentenénk hanem a feladat leírását bővítenénk (pl.: segítség kérés formájában) vagy segítő kérdéseket tennénk fel, hogy jobban megértse a problémát és magától tudja beírni a helyes megoldást még akár úgy is, hogy 2-3. segítség már szinte megadja a helyes választ 
Továbbá ha elrontja a diák részfeladatot akkor felajánlunk neki több lehetőséget:

- Újra megpróbálom 
- Kérek egy kis segítséget (ha még van)
- Könnyebb feladatra ugrás (csak ha már több részfeladatot is többször elrontott)
- Részfeladat kihagyása (ez nem bitos, hogy minden feladatnál jó, és a maradék feladat megértését is ronthatja, de egyes részfeladatoknál lehetne ilyen opció)

Sőt akár itt alternatív részfeladatot is feljánlhatunk ha már kifogyott a diák a segítségekből, de ne minden részfeladatnál. A lényeg hogy ne egyből kínáljuk fel a helyes megoldást.

A flow-ban nem az a lényeg, hogy ha valami nem megy akkor mindig van kerülőút hanem az, hogy amit csinálunk akár milyen nehéz is mindig látjuk a következő lépést amerre mehetünk és ez biztosítja az áramlat érményt. De a segítség megválasztása is opcionális kell, hogy legyen mert lehet, hogy valaki szeret küzdeni a feladattal...

**Comment by zsebtanar** [comment]
Ez sztem egy tipikusan olyan terület, amit érdemes tesztelni, és a
visszajelzések alapján tudjuk majd eldönteni, hogy melyik módszernek milyen
előnyei/nehézségei vannak. Én személy szerint el tudom képzelni, hogy
lesznek olyanok, akik még az összes segítő kérdés után sem fogják tudni a
megoldást, és ha újra megpróbálják, ugyanúgy el fognak akadni. A könnyebb
feladatra ugrás sztem jó ötlet, ez ha emlékszel még, anno bennem is
megfogalmazódott (hogy kvázi minden feladatnak van egy "előkövetelménye"
(dependencies - szép magyar szóval :D), és a felhasználó rá tud kattintani
az egyes "előfeladatokra" (amiknek szintén vannak előkövetelményei stb.).

Amúgy ahhoz mit szólsz, ha az elején játékmódot választhat a felhasználó,
amivel ő tudja eldönteni, hogy milyen fajta segítséget szeretne kérni? Ez
akár a gamification része is lehet :)

[image: Szövegközi kép 1]

2017. november 28. 15:49 László Vadász írta, <notifications@github.com>:

**Comment by maxinteger** [comment]
Szerintem a részfeladatok alapfunkcióit már korábban sikerült tisztáyni ezért, ezt a feladatot átnevem és létrehozok egy külön issue-t amin tudok dolgozni amíg megvitatjuk az extra funkciókat

**Comment by zsebtanar** [comment]
Rendben.

László Vadász <notifications@github.com> ezt írta (időpont: 2017. nov. 29.,
Sze 10:16):

**Comment by maxinteger** [comment]
@zsebtanar Ez a feladat még aktuális?
