### ISSUE TITLE
Beviteli mező - igaz-hamis

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#8]

**Comment by maxinteger** [comment]
@zsebtanar Ehhez nem biztos, hogy kell külön beviteli mező mert meg lehet oldani felelet választóval is. De ha más elképzelésed van erről a mezőről akkor kérlek részletezd vagy mustass egy példát

**Comment by zsebtanar** [comment]
sztem célszerű külön venni (kényelmi okokból). a példát a redmentából vettem: 
![image](https://user-images.githubusercontent.com/13850825/28156380-c813d0fa-67b2-11e7-8272-f30c719b46a7.png)

**Comment by maxinteger** [comment]
@zsebtanar köszi a példát így már sokkal érthetőbb valóban más komponensről van szó.

**Comment by maxinteger** [comment]
végre kész :)

**Comment by zsebtanar** [comment]
@maxinteger köszi szépen! ez már elérhető a honlapon?
