### ISSUE TITLE
Captcha telepítése

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#86]
A Captcha segítségével megelőzhető, hogy webes robotok generált üzenetekkel/felhasználókkal szemeteljék tele a Zsebtanárt.

Több szempontból is hasznos lenne beállítsani
- valódi felhasználók védelme
- rendszer védelme
- túl sok rosszindulatú lekérdezés növelheti a szerver kaidásainkat

Lényegében minden form esetében szükségünk lenne védelemre:
- regisztráció
- bejelentkezés
- visszajelzés/feladat beküldés
- feladat megoldás beküldés (ebben nem vagyok telejsen biztos)

Lehetésges opciók:
 - [Google reCaptcha](https://developers.google.com/recaptcha/)

**Comment by zsebtanar** [comment]
támogatom!

2017. október 9. 13:26 László Vadász írta, <notifications@github.com>:

**Comment by zsebtanar** [comment]
ezt lezárom, ha nem gond.
