### ISSUE TITLE
Képfeltöltés feladathoz

### ISSUE THREAD

**Issue by maxinteger** [zsebtanar/zsebtanar-proto#87]
Jelenleg akár több feladat között is megoszthatóak a képek, de valójában ez egy felesleges funkció és csak túlbonyolítja a felületet és a működést.

Helyette egy feladatszintű megközelítésre van szükség, tehát a feladat szerkesztőn belül bármennyiszer újrahasznosítható egy feltöltött kép, de más feladatból már nem érhető el.

## Képfeltöltés

A feladatok estében a képfeltöltés két részre bomlik.

1. Kép beillesztése a feladatba (itt már használható a kép)
2. A feladat mentésekor előbb feltöltjük az új képeket és csak ezt követően tároljuk el a feladatot.

Ehhez szükség lesz egy `resource` objektumra a feladaton belül
```
...
{
   resource: {
      [FB-ID]: {
         image: ...
         name: ''
         width: 100
         height: 100
      }
   }
}
```

Az `image` tulajdonság több értéket is felvehet

- `File` - amikor új képet adunk a feladathoz
- kép storage útvonal - a kép feltöltés után de még a feladat mentése előtt
- végleges kép URL - a `kép storage útvonal` alapján létrehozott `download url`, ezt a cloud function fogja létrehozni.

## Markdown
Sajnos a markdown alap képbeszúrása nem alkalmas a beszúrt képek követésére így szükséges egy új formtáum (ez alapján: https://www.npmjs.com/package/markdown-it-imsize):

    +[Kép címke](kép =WxH) 
 
Ahol a W és a H opcionális

    <img src="kép-url" alt="Kép címe" width="W" height="H"/>

## Feladatok

- [ ] új kép markdown plugin
- [ ] `resource` objektum
- [ ] cloud function frissítése
- [ ] referencia számlálás (ha nincs hivatkozás egy feltöltött képre a mentés után akkor törölni kell a képet)

## Limitációk 

- egyenlőre nem készítünk előnézeti képet a feltöltött fájlokból
- egyenlőre csak képet lehet a felathoz csatolni

**Comment by zsebtanar** [comment]
egy apró kérdés: kép igazítására van lehetőség?

2017. október 9. 16:03 László Vadász írta, <notifications@github.com>:

**Comment by maxinteger** [comment]
@zsebtanar ez a feladat csak a kép feltöltés alapokat tartalmazta.
Ebbe nem tartozik bele sok apróság mint például a kép igazítás sem, egyébként a markdown eleve nem támogatja a szöveg igazítást mert eredetileg folyó szövegre találták ki ahol az oldal végtelen hosszú és tetszőlegesen széles, utóbbi miatt nem mindig néz ki jól a középre/jobb igazított szöveg.

Ezzel kapcsolatban felveszek egy külön feladatot.

**Comment by zsebtanar** [comment]
Értem. Végülis lehet, hogy így is jó lesz.

László Vadász <notifications@github.com> ezt írta (időpont: 2018. febr.
28., Sze 22:21):
