### ISSUE TITLE
Többszörös kattintás a segítségre

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#93]
Ha többször kattintok a segítség gombra, többször írja ki ugyanazt a segítséget:
![image](https://user-images.githubusercontent.com/13850825/32980289-e689deec-cc63-11e7-9af7-60aa493a9c5c.png)

**Comment by maxinteger** [comment]
Mostantól ha lekérdezzük a következő segítséget akkor inaktívvá válik a gomb és egy forgó fogaskerék jelzi a szerverre várakozást (ez akár 10-20 másodperc is lehet ha a szerver túl sokáig volt inaktív)
