### ISSUE TITLE
Keresés a főoldalon nem működik

### ISSUE THREAD

**Issue by zsebtanar** [zsebtanar/zsebtanar-proto#95]
![image](https://user-images.githubusercontent.com/13850825/32980338-b4d78d1c-cc64-11e7-89e8-a4f171a3fed1.png)

**Comment by maxinteger** [comment]
@zsebtanar 
Módosítottam a viselkedést:
- ha rákattintasz a mezőre akkor átugrik a kereső oldalra
- ha elkezdesz írni és több mint 0.8 másodpercig nem ütsz le billentyűt akkor beírt szöveggel együtt átugrik a kereső oldalra
